// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency @unsafe public import struct Foundation.URL
@preconcurrency @unsafe public import struct Foundation.Data
@preconcurrency @unsafe public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/NewsArticleCreateSchema`.
        public struct NewsArticleCreateSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NewsArticleCreateSchema/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsArticleCreateSchema/excerpt`.
            public var excerpt: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsArticleCreateSchema/content`.
            public var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsArticleCreateSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsArticleCreateSchema/categoryIds`.
            public var categoryIds: Components.Schemas.NewsAdminOpenAPIComponentsCategoryIDsField?
            /// - Remark: Generated from `#/components/schemas/NewsArticleCreateSchema/metadata`.
            public var metadata: Components.Schemas.NewsMetadataInputSchema
            /// Creates a new `NewsArticleCreateSchema`.
            ///
            /// - Parameters:
            ///   - title:
            ///   - excerpt:
            ///   - content:
            ///   - imageAssetId:
            ///   - categoryIds:
            ///   - metadata:
            public init(
                title: Swift.String,
                excerpt: Swift.String,
                content: Swift.String,
                imageAssetId: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                categoryIds: Components.Schemas.NewsAdminOpenAPIComponentsCategoryIDsField? = nil,
                metadata: Components.Schemas.NewsMetadataInputSchema
            ) {
                self.title = title
                self.excerpt = excerpt
                self.content = content
                self.imageAssetId = imageAssetId
                self.categoryIds = categoryIds
                self.metadata = metadata
            }
            public enum CodingKeys: String, CodingKey {
                case title
                case excerpt
                case content
                case imageAssetId
                case categoryIds
                case metadata
            }
        }
        /// - Remark: Generated from `#/components/schemas/NewsAdminOpenAPIComponentsStringField`.
        public typealias NewsAdminOpenAPIComponentsStringField = Swift.String
        /// - Remark: Generated from `#/components/schemas/NewsAdminOpenAPIComponentsCategoryIDsField`.
        public typealias NewsAdminOpenAPIComponentsCategoryIDsField = [Components.Schemas.NewsAdminOpenAPIComponentsStringField]
        /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema`.
        public struct NewsMetadataInputSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/slug`.
            public var slug: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/status`.
            public var status: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/publicationDate`.
            public var publicationDate: Components.Schemas.NewsAdminOpenAPIComponentsTimestampField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/expirationDate`.
            public var expirationDate: Components.Schemas.NewsAdminOpenAPIComponentsTimestampField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/title`.
            public var title: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/excerpt`.
            public var excerpt: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/imageURL`.
            public var imageURL: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/canonicalURL`.
            public var canonicalURL: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/noIndex`.
            public var noIndex: Components.Schemas.NewsAdminOpenAPIComponentsBooleanField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/primaryKeyword`.
            public var primaryKeyword: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/cssCodeInjection`.
            public var cssCodeInjection: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/javascriptCodeInjection`.
            public var javascriptCodeInjection: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataInputSchema/structuredDataCodeInjection`.
            public var structuredDataCodeInjection: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// Creates a new `NewsMetadataInputSchema`.
            ///
            /// - Parameters:
            ///   - slug:
            ///   - status:
            ///   - publicationDate:
            ///   - expirationDate:
            ///   - title:
            ///   - excerpt:
            ///   - imageURL:
            ///   - canonicalURL:
            ///   - noIndex:
            ///   - primaryKeyword:
            ///   - cssCodeInjection:
            ///   - javascriptCodeInjection:
            ///   - structuredDataCodeInjection:
            public init(
                slug: Swift.String,
                status: Swift.String,
                publicationDate: Components.Schemas.NewsAdminOpenAPIComponentsTimestampField? = nil,
                expirationDate: Components.Schemas.NewsAdminOpenAPIComponentsTimestampField? = nil,
                title: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                excerpt: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                imageURL: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                canonicalURL: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                noIndex: Components.Schemas.NewsAdminOpenAPIComponentsBooleanField? = nil,
                primaryKeyword: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                cssCodeInjection: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                javascriptCodeInjection: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                structuredDataCodeInjection: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil
            ) {
                self.slug = slug
                self.status = status
                self.publicationDate = publicationDate
                self.expirationDate = expirationDate
                self.title = title
                self.excerpt = excerpt
                self.imageURL = imageURL
                self.canonicalURL = canonicalURL
                self.noIndex = noIndex
                self.primaryKeyword = primaryKeyword
                self.cssCodeInjection = cssCodeInjection
                self.javascriptCodeInjection = javascriptCodeInjection
                self.structuredDataCodeInjection = structuredDataCodeInjection
            }
            public enum CodingKeys: String, CodingKey {
                case slug
                case status
                case publicationDate
                case expirationDate
                case title
                case excerpt
                case imageURL
                case canonicalURL
                case noIndex
                case primaryKeyword
                case cssCodeInjection
                case javascriptCodeInjection
                case structuredDataCodeInjection
            }
        }
        /// - Remark: Generated from `#/components/schemas/NewsAdminOpenAPIComponentsTimestampField`.
        public typealias NewsAdminOpenAPIComponentsTimestampField = Swift.Double
        /// - Remark: Generated from `#/components/schemas/NewsAdminOpenAPIComponentsBooleanField`.
        public typealias NewsAdminOpenAPIComponentsBooleanField = Swift.Bool
        /// - Remark: Generated from `#/components/schemas/NewsArticleDetailSchema`.
        public struct NewsArticleDetailSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NewsArticleDetailSchema/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsArticleDetailSchema/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsArticleDetailSchema/excerpt`.
            public var excerpt: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsArticleDetailSchema/content`.
            public var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsArticleDetailSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsArticleDetailSchema/categoryIds`.
            public var categoryIds: [Components.Schemas.NewsAdminOpenAPIComponentsStringField]
            /// - Remark: Generated from `#/components/schemas/NewsArticleDetailSchema/metadata`.
            public var metadata: Components.Schemas.NewsMetadataDetailSchema
            /// - Remark: Generated from `#/components/schemas/NewsArticleDetailSchema/createdAt`.
            public var createdAt: Swift.Double
            /// - Remark: Generated from `#/components/schemas/NewsArticleDetailSchema/updatedAt`.
            public var updatedAt: Swift.Double
            /// Creates a new `NewsArticleDetailSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - title:
            ///   - excerpt:
            ///   - content:
            ///   - imageAssetId:
            ///   - categoryIds:
            ///   - metadata:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Swift.String,
                title: Swift.String,
                excerpt: Swift.String,
                content: Swift.String,
                imageAssetId: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                categoryIds: [Components.Schemas.NewsAdminOpenAPIComponentsStringField],
                metadata: Components.Schemas.NewsMetadataDetailSchema,
                createdAt: Swift.Double,
                updatedAt: Swift.Double
            ) {
                self.id = id
                self.title = title
                self.excerpt = excerpt
                self.content = content
                self.imageAssetId = imageAssetId
                self.categoryIds = categoryIds
                self.metadata = metadata
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case title
                case excerpt
                case content
                case imageAssetId
                case categoryIds
                case metadata
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema`.
        public struct NewsMetadataDetailSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/referenceType`.
            public var referenceType: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/referenceID`.
            public var referenceID: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/slug`.
            public var slug: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/template`.
            public var template: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/publicationDate`.
            public var publicationDate: Swift.Double
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/expirationDate`.
            public var expirationDate: Components.Schemas.NewsAdminOpenAPIComponentsTimestampField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/status`.
            public var status: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/title`.
            public var title: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/excerpt`.
            public var excerpt: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/imageURL`.
            public var imageURL: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/canonicalURL`.
            public var canonicalURL: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/noIndex`.
            public var noIndex: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/primaryKeyword`.
            public var primaryKeyword: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/cssCodeInjection`.
            public var cssCodeInjection: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/javascriptCodeInjection`.
            public var javascriptCodeInjection: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/structuredDataCodeInjection`.
            public var structuredDataCodeInjection: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/createdAt`.
            public var createdAt: Swift.Double
            /// - Remark: Generated from `#/components/schemas/NewsMetadataDetailSchema/updatedAt`.
            public var updatedAt: Swift.Double
            /// Creates a new `NewsMetadataDetailSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - referenceType:
            ///   - referenceID:
            ///   - slug:
            ///   - template:
            ///   - publicationDate:
            ///   - expirationDate:
            ///   - status:
            ///   - title:
            ///   - excerpt:
            ///   - imageURL:
            ///   - canonicalURL:
            ///   - noIndex:
            ///   - primaryKeyword:
            ///   - cssCodeInjection:
            ///   - javascriptCodeInjection:
            ///   - structuredDataCodeInjection:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Swift.String,
                referenceType: Swift.String,
                referenceID: Swift.String,
                slug: Swift.String,
                template: Swift.String,
                publicationDate: Swift.Double,
                expirationDate: Components.Schemas.NewsAdminOpenAPIComponentsTimestampField? = nil,
                status: Swift.String,
                title: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                excerpt: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                imageURL: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                canonicalURL: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                noIndex: Swift.Bool,
                primaryKeyword: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                cssCodeInjection: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                javascriptCodeInjection: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                structuredDataCodeInjection: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                createdAt: Swift.Double,
                updatedAt: Swift.Double
            ) {
                self.id = id
                self.referenceType = referenceType
                self.referenceID = referenceID
                self.slug = slug
                self.template = template
                self.publicationDate = publicationDate
                self.expirationDate = expirationDate
                self.status = status
                self.title = title
                self.excerpt = excerpt
                self.imageURL = imageURL
                self.canonicalURL = canonicalURL
                self.noIndex = noIndex
                self.primaryKeyword = primaryKeyword
                self.cssCodeInjection = cssCodeInjection
                self.javascriptCodeInjection = javascriptCodeInjection
                self.structuredDataCodeInjection = structuredDataCodeInjection
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case referenceType
                case referenceID
                case slug
                case template
                case publicationDate
                case expirationDate
                case status
                case title
                case excerpt
                case imageURL
                case canonicalURL
                case noIndex
                case primaryKeyword
                case cssCodeInjection
                case javascriptCodeInjection
                case structuredDataCodeInjection
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/DeleteRequestSchema`.
        public struct DeleteRequestSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/DeleteRequestSchema/ids`.
            public var ids: [Swift.String]
            /// - Remark: Generated from `#/components/schemas/DeleteRequestSchema/results`.
            public var results: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/DeleteRequestSchema/summary`.
            public var summary: Swift.Bool
            /// Creates a new `DeleteRequestSchema`.
            ///
            /// - Parameters:
            ///   - ids:
            ///   - results:
            ///   - summary:
            public init(
                ids: [Swift.String],
                results: Swift.Bool,
                summary: Swift.Bool
            ) {
                self.ids = ids
                self.results = results
                self.summary = summary
            }
            public enum CodingKeys: String, CodingKey {
                case ids
                case results
                case summary
            }
        }
        /// - Remark: Generated from `#/components/schemas/DeleteResponseSchema`.
        public struct DeleteResponseSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/DeleteResponseSchema/results`.
            public var results: Components.Schemas.DeleteResultListSchema?
            /// - Remark: Generated from `#/components/schemas/DeleteResponseSchema/summary`.
            public var summary: Components.Schemas.DeleteSummarySchema?
            /// Creates a new `DeleteResponseSchema`.
            ///
            /// - Parameters:
            ///   - results:
            ///   - summary:
            public init(
                results: Components.Schemas.DeleteResultListSchema? = nil,
                summary: Components.Schemas.DeleteSummarySchema? = nil
            ) {
                self.results = results
                self.summary = summary
            }
            public enum CodingKeys: String, CodingKey {
                case results
                case summary
            }
        }
        /// - Remark: Generated from `#/components/schemas/DeleteResultListSchema`.
        public struct DeleteResultListSchemaPayload: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/DeleteResultListSchema/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/DeleteResultListSchema/status`.
            @frozen public enum StatusPayload: String, Codable, Hashable, Sendable, CaseIterable {
                case deleted = "deleted"
                case notFound = "not_found"
                case forbidden = "forbidden"
            }
            /// - Remark: Generated from `#/components/schemas/DeleteResultListSchema/status`.
            public var status: Components.Schemas.DeleteResultListSchemaPayload.StatusPayload
            /// Creates a new `DeleteResultListSchemaPayload`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - status:
            public init(
                id: Swift.String,
                status: Components.Schemas.DeleteResultListSchemaPayload.StatusPayload
            ) {
                self.id = id
                self.status = status
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case status
            }
        }
        /// - Remark: Generated from `#/components/schemas/DeleteResultListSchema`.
        public typealias DeleteResultListSchema = [Components.Schemas.DeleteResultListSchemaPayload]
        /// - Remark: Generated from `#/components/schemas/DeleteSummarySchema`.
        public struct DeleteSummarySchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/DeleteSummarySchema/requested`.
            public var requested: Swift.Int
            /// - Remark: Generated from `#/components/schemas/DeleteSummarySchema/deleted`.
            public var deleted: Swift.Int
            /// - Remark: Generated from `#/components/schemas/DeleteSummarySchema/omitted`.
            public var omitted: Swift.Int
            /// Creates a new `DeleteSummarySchema`.
            ///
            /// - Parameters:
            ///   - requested:
            ///   - deleted:
            ///   - omitted:
            public init(
                requested: Swift.Int,
                deleted: Swift.Int,
                omitted: Swift.Int
            ) {
                self.requested = requested
                self.deleted = deleted
                self.omitted = omitted
            }
            public enum CodingKeys: String, CodingKey {
                case requested
                case deleted
                case omitted
            }
        }
        /// - Remark: Generated from `#/components/schemas/NewsArticleListSchema`.
        public typealias NewsArticleListSchema = [Components.Schemas.NewsArticleListItemSchema]
        /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSchema`.
        public struct NewsArticleListItemSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSchema/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSchema/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSchema/excerpt`.
            public var excerpt: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSchema/createdAt`.
            public var createdAt: Swift.Double
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSchema/updatedAt`.
            public var updatedAt: Swift.Double
            /// Creates a new `NewsArticleListItemSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - title:
            ///   - excerpt:
            ///   - imageAssetId:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Swift.String,
                title: Swift.String,
                excerpt: Swift.String,
                imageAssetId: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                createdAt: Swift.Double,
                updatedAt: Swift.Double
            ) {
                self.id = id
                self.title = title
                self.excerpt = excerpt
                self.imageAssetId = imageAssetId
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case title
                case excerpt
                case imageAssetId
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchQuerySchema`.
        public struct NewsArticleListItemSearchQuerySchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchQuerySchema/page`.
            public var page: Components.Schemas.SearchPageSchema
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchQuerySchema/SortPayload`.
            public struct SortPayloadPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchQuerySchema/SortPayload/field`.
                @frozen public enum FieldPayload: String, Codable, Hashable, Sendable, CaseIterable {
                    case id = "id"
                    case title = "title"
                    case createdAt = "createdAt"
                    case updatedAt = "updatedAt"
                }
                /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchQuerySchema/SortPayload/field`.
                public var field: Components.Schemas.NewsArticleListItemSearchQuerySchema.SortPayloadPayload.FieldPayload
                /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchQuerySchema/SortPayload/direction`.
                public var direction: Components.Schemas.SortDirection
                /// Creates a new `SortPayloadPayload`.
                ///
                /// - Parameters:
                ///   - field:
                ///   - direction:
                public init(
                    field: Components.Schemas.NewsArticleListItemSearchQuerySchema.SortPayloadPayload.FieldPayload,
                    direction: Components.Schemas.SortDirection
                ) {
                    self.field = field
                    self.direction = direction
                }
                public enum CodingKeys: String, CodingKey {
                    case field
                    case direction
                }
            }
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchQuerySchema/sort`.
            public typealias SortPayload = [Components.Schemas.NewsArticleListItemSearchQuerySchema.SortPayloadPayload]
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchQuerySchema/sort`.
            public var sort: Components.Schemas.NewsArticleListItemSearchQuerySchema.SortPayload?
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchQuerySchema/filters`.
            public struct FiltersPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchQuerySchema/filters/search`.
                public var search: Components.Schemas.SearchStringField?
                /// Creates a new `FiltersPayload`.
                ///
                /// - Parameters:
                ///   - search:
                public init(search: Components.Schemas.SearchStringField? = nil) {
                    self.search = search
                }
                public enum CodingKeys: String, CodingKey {
                    case search
                }
            }
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchQuerySchema/filters`.
            public var filters: Components.Schemas.NewsArticleListItemSearchQuerySchema.FiltersPayload
            /// Creates a new `NewsArticleListItemSearchQuerySchema`.
            ///
            /// - Parameters:
            ///   - page:
            ///   - sort:
            ///   - filters:
            public init(
                page: Components.Schemas.SearchPageSchema,
                sort: Components.Schemas.NewsArticleListItemSearchQuerySchema.SortPayload? = nil,
                filters: Components.Schemas.NewsArticleListItemSearchQuerySchema.FiltersPayload
            ) {
                self.page = page
                self.sort = sort
                self.filters = filters
            }
            public enum CodingKeys: String, CodingKey {
                case page
                case sort
                case filters
            }
        }
        /// - Remark: Generated from `#/components/schemas/SearchPageSchema`.
        public struct SearchPageSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SearchPageSchema/size`.
            public var size: Components.Schemas.SearchPageSizeField
            /// - Remark: Generated from `#/components/schemas/SearchPageSchema/number`.
            public var number: Components.Schemas.SearchPageNumberField
            /// Creates a new `SearchPageSchema`.
            ///
            /// - Parameters:
            ///   - size:
            ///   - number:
            public init(
                size: Components.Schemas.SearchPageSizeField,
                number: Components.Schemas.SearchPageNumberField
            ) {
                self.size = size
                self.number = number
            }
            public enum CodingKeys: String, CodingKey {
                case size
                case number
            }
        }
        /// - Remark: Generated from `#/components/schemas/SearchPageSizeField`.
        public typealias SearchPageSizeField = Swift.Int
        /// - Remark: Generated from `#/components/schemas/SearchPageNumberField`.
        public typealias SearchPageNumberField = Swift.Int
        /// - Remark: Generated from `#/components/schemas/SortDirection`.
        @frozen public enum SortDirection: String, Codable, Hashable, Sendable, CaseIterable {
            case asc = "asc"
            case desc = "desc"
        }
        /// - Remark: Generated from `#/components/schemas/SearchStringField`.
        public typealias SearchStringField = Swift.String
        /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchSchema`.
        public struct NewsArticleListItemSearchSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchSchema/query`.
            public var query: Components.Schemas.NewsArticleListItemSearchQuerySchema
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchSchema/data`.
            public struct DataPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchSchema/data/items`.
                public var items: [Components.Schemas.NewsArticleListItemSchema]
                /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchSchema/data/total`.
                public var total: Swift.Int
                /// Creates a new `DataPayload`.
                ///
                /// - Parameters:
                ///   - items:
                ///   - total:
                public init(
                    items: [Components.Schemas.NewsArticleListItemSchema],
                    total: Swift.Int
                ) {
                    self.items = items
                    self.total = total
                }
                public enum CodingKeys: String, CodingKey {
                    case items
                    case total
                }
            }
            /// - Remark: Generated from `#/components/schemas/NewsArticleListItemSearchSchema/data`.
            public var data: Components.Schemas.NewsArticleListItemSearchSchema.DataPayload
            /// Creates a new `NewsArticleListItemSearchSchema`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - data:
            public init(
                query: Components.Schemas.NewsArticleListItemSearchQuerySchema,
                data: Components.Schemas.NewsArticleListItemSearchSchema.DataPayload
            ) {
                self.query = query
                self.data = data
            }
            public enum CodingKeys: String, CodingKey {
                case query
                case data
            }
        }
        /// - Remark: Generated from `#/components/schemas/NewsCategoryCreateSchema`.
        public struct NewsCategoryCreateSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NewsCategoryCreateSchema/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsCategoryCreateSchema/excerpt`.
            public var excerpt: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsCategoryCreateSchema/content`.
            public var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsCategoryCreateSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsCategoryCreateSchema/metadata`.
            public var metadata: Components.Schemas.NewsMetadataInputSchema
            /// Creates a new `NewsCategoryCreateSchema`.
            ///
            /// - Parameters:
            ///   - title:
            ///   - excerpt:
            ///   - content:
            ///   - imageAssetId:
            ///   - metadata:
            public init(
                title: Swift.String,
                excerpt: Swift.String,
                content: Swift.String,
                imageAssetId: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                metadata: Components.Schemas.NewsMetadataInputSchema
            ) {
                self.title = title
                self.excerpt = excerpt
                self.content = content
                self.imageAssetId = imageAssetId
                self.metadata = metadata
            }
            public enum CodingKeys: String, CodingKey {
                case title
                case excerpt
                case content
                case imageAssetId
                case metadata
            }
        }
        /// - Remark: Generated from `#/components/schemas/NewsCategoryDetailSchema`.
        public struct NewsCategoryDetailSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NewsCategoryDetailSchema/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsCategoryDetailSchema/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsCategoryDetailSchema/excerpt`.
            public var excerpt: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsCategoryDetailSchema/content`.
            public var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsCategoryDetailSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsCategoryDetailSchema/metadata`.
            public var metadata: Components.Schemas.NewsMetadataDetailSchema
            /// - Remark: Generated from `#/components/schemas/NewsCategoryDetailSchema/createdAt`.
            public var createdAt: Swift.Double
            /// - Remark: Generated from `#/components/schemas/NewsCategoryDetailSchema/updatedAt`.
            public var updatedAt: Swift.Double
            /// Creates a new `NewsCategoryDetailSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - title:
            ///   - excerpt:
            ///   - content:
            ///   - imageAssetId:
            ///   - metadata:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Swift.String,
                title: Swift.String,
                excerpt: Swift.String,
                content: Swift.String,
                imageAssetId: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                metadata: Components.Schemas.NewsMetadataDetailSchema,
                createdAt: Swift.Double,
                updatedAt: Swift.Double
            ) {
                self.id = id
                self.title = title
                self.excerpt = excerpt
                self.content = content
                self.imageAssetId = imageAssetId
                self.metadata = metadata
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case title
                case excerpt
                case content
                case imageAssetId
                case metadata
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/NewsCategoryListSchema`.
        public typealias NewsCategoryListSchema = [Components.Schemas.NewsCategoryListItemSchema]
        /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSchema`.
        public struct NewsCategoryListItemSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSchema/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSchema/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSchema/excerpt`.
            public var excerpt: Swift.String
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.NewsAdminOpenAPIComponentsStringField?
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSchema/createdAt`.
            public var createdAt: Swift.Double
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSchema/updatedAt`.
            public var updatedAt: Swift.Double
            /// Creates a new `NewsCategoryListItemSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - title:
            ///   - excerpt:
            ///   - imageAssetId:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Swift.String,
                title: Swift.String,
                excerpt: Swift.String,
                imageAssetId: Components.Schemas.NewsAdminOpenAPIComponentsStringField? = nil,
                createdAt: Swift.Double,
                updatedAt: Swift.Double
            ) {
                self.id = id
                self.title = title
                self.excerpt = excerpt
                self.imageAssetId = imageAssetId
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case title
                case excerpt
                case imageAssetId
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchQuerySchema`.
        public struct NewsCategoryListItemSearchQuerySchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchQuerySchema/page`.
            public var page: Components.Schemas.SearchPageSchema
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchQuerySchema/SortPayload`.
            public struct SortPayloadPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchQuerySchema/SortPayload/field`.
                @frozen public enum FieldPayload: String, Codable, Hashable, Sendable, CaseIterable {
                    case id = "id"
                    case title = "title"
                    case createdAt = "createdAt"
                    case updatedAt = "updatedAt"
                }
                /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchQuerySchema/SortPayload/field`.
                public var field: Components.Schemas.NewsCategoryListItemSearchQuerySchema.SortPayloadPayload.FieldPayload
                /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchQuerySchema/SortPayload/direction`.
                public var direction: Components.Schemas.SortDirection
                /// Creates a new `SortPayloadPayload`.
                ///
                /// - Parameters:
                ///   - field:
                ///   - direction:
                public init(
                    field: Components.Schemas.NewsCategoryListItemSearchQuerySchema.SortPayloadPayload.FieldPayload,
                    direction: Components.Schemas.SortDirection
                ) {
                    self.field = field
                    self.direction = direction
                }
                public enum CodingKeys: String, CodingKey {
                    case field
                    case direction
                }
            }
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchQuerySchema/sort`.
            public typealias SortPayload = [Components.Schemas.NewsCategoryListItemSearchQuerySchema.SortPayloadPayload]
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchQuerySchema/sort`.
            public var sort: Components.Schemas.NewsCategoryListItemSearchQuerySchema.SortPayload?
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchQuerySchema/filters`.
            public struct FiltersPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchQuerySchema/filters/search`.
                public var search: Components.Schemas.SearchStringField?
                /// Creates a new `FiltersPayload`.
                ///
                /// - Parameters:
                ///   - search:
                public init(search: Components.Schemas.SearchStringField? = nil) {
                    self.search = search
                }
                public enum CodingKeys: String, CodingKey {
                    case search
                }
            }
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchQuerySchema/filters`.
            public var filters: Components.Schemas.NewsCategoryListItemSearchQuerySchema.FiltersPayload
            /// Creates a new `NewsCategoryListItemSearchQuerySchema`.
            ///
            /// - Parameters:
            ///   - page:
            ///   - sort:
            ///   - filters:
            public init(
                page: Components.Schemas.SearchPageSchema,
                sort: Components.Schemas.NewsCategoryListItemSearchQuerySchema.SortPayload? = nil,
                filters: Components.Schemas.NewsCategoryListItemSearchQuerySchema.FiltersPayload
            ) {
                self.page = page
                self.sort = sort
                self.filters = filters
            }
            public enum CodingKeys: String, CodingKey {
                case page
                case sort
                case filters
            }
        }
        /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchSchema`.
        public struct NewsCategoryListItemSearchSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchSchema/query`.
            public var query: Components.Schemas.NewsCategoryListItemSearchQuerySchema
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchSchema/data`.
            public struct DataPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchSchema/data/items`.
                public var items: [Components.Schemas.NewsCategoryListItemSchema]
                /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchSchema/data/total`.
                public var total: Swift.Int
                /// Creates a new `DataPayload`.
                ///
                /// - Parameters:
                ///   - items:
                ///   - total:
                public init(
                    items: [Components.Schemas.NewsCategoryListItemSchema],
                    total: Swift.Int
                ) {
                    self.items = items
                    self.total = total
                }
                public enum CodingKeys: String, CodingKey {
                    case items
                    case total
                }
            }
            /// - Remark: Generated from `#/components/schemas/NewsCategoryListItemSearchSchema/data`.
            public var data: Components.Schemas.NewsCategoryListItemSearchSchema.DataPayload
            /// Creates a new `NewsCategoryListItemSearchSchema`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - data:
            public init(
                query: Components.Schemas.NewsCategoryListItemSearchQuerySchema,
                data: Components.Schemas.NewsCategoryListItemSearchSchema.DataPayload
            ) {
                self.query = query
                self.data = data
            }
            public enum CodingKeys: String, CodingKey {
                case query
                case data
            }
        }
    }
}

// swift-openapi-generator dummy public import compatibility
public func unsafeOpenAPIGenerationHotfixForAppNewsAdminModuleAdminTypesComponentsSchemas(
    _ url: Foundation.URL,
    _ data: Foundation.Data,
    _ date: Foundation.Date,
    _ runtimeConfiguration: OpenAPIRuntime.Configuration
) {
    fatalError()
}
