// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency @unsafe public import struct Foundation.URL
@preconcurrency @unsafe public import struct Foundation.Data
@preconcurrency @unsafe public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/BlogPostCreateSchema`.
        public struct BlogPostCreateSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogPostCreateSchema/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogPostCreateSchema/excerpt`.
            public var excerpt: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogPostCreateSchema/content`.
            public var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogPostCreateSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.BlogPostImageAssetIdField?
            /// - Remark: Generated from `#/components/schemas/BlogPostCreateSchema/authorIds`.
            public var authorIds: Components.Schemas.BlogPostAuthorIdsField?
            /// - Remark: Generated from `#/components/schemas/BlogPostCreateSchema/tagIds`.
            public var tagIds: Components.Schemas.BlogPostTagIdsField?
            /// Creates a new `BlogPostCreateSchema`.
            ///
            /// - Parameters:
            ///   - title:
            ///   - excerpt:
            ///   - content:
            ///   - imageAssetId:
            ///   - authorIds:
            ///   - tagIds:
            public init(
                title: Swift.String,
                excerpt: Swift.String,
                content: Swift.String,
                imageAssetId: Components.Schemas.BlogPostImageAssetIdField? = nil,
                authorIds: Components.Schemas.BlogPostAuthorIdsField? = nil,
                tagIds: Components.Schemas.BlogPostTagIdsField? = nil
            ) {
                self.title = title
                self.excerpt = excerpt
                self.content = content
                self.imageAssetId = imageAssetId
                self.authorIds = authorIds
                self.tagIds = tagIds
            }
            public enum CodingKeys: String, CodingKey {
                case title
                case excerpt
                case content
                case imageAssetId
                case authorIds
                case tagIds
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogPostImageAssetIdField`.
        public typealias BlogPostImageAssetIdField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogPostAuthorIdsField`.
        public typealias BlogPostAuthorIdsField = [Components.Schemas.BlogAuthorIdField]
        /// - Remark: Generated from `#/components/schemas/BlogAuthorIdField`.
        public typealias BlogAuthorIdField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogPostTagIdsField`.
        public typealias BlogPostTagIdsField = [Components.Schemas.BlogTagIdField]
        /// - Remark: Generated from `#/components/schemas/BlogTagIdField`.
        public typealias BlogTagIdField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogPostDetailSchema`.
        public struct BlogPostDetailSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogPostDetailSchema/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogPostDetailSchema/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogPostDetailSchema/excerpt`.
            public var excerpt: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogPostDetailSchema/content`.
            public var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogPostDetailSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.BlogPostImageAssetIdField?
            /// - Remark: Generated from `#/components/schemas/BlogPostDetailSchema/authorIds`.
            public var authorIds: Components.Schemas.BlogPostAuthorIdsField
            /// - Remark: Generated from `#/components/schemas/BlogPostDetailSchema/tagIds`.
            public var tagIds: Components.Schemas.BlogPostTagIdsField
            /// - Remark: Generated from `#/components/schemas/BlogPostDetailSchema/metadata`.
            public var metadata: Components.Schemas.WebMetadataDetailSchema
            /// - Remark: Generated from `#/components/schemas/BlogPostDetailSchema/createdAt`.
            public var createdAt: Swift.Double
            /// - Remark: Generated from `#/components/schemas/BlogPostDetailSchema/updatedAt`.
            public var updatedAt: Swift.Double
            /// Creates a new `BlogPostDetailSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - title:
            ///   - excerpt:
            ///   - content:
            ///   - imageAssetId:
            ///   - authorIds:
            ///   - tagIds:
            ///   - metadata:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Swift.String,
                title: Swift.String,
                excerpt: Swift.String,
                content: Swift.String,
                imageAssetId: Components.Schemas.BlogPostImageAssetIdField? = nil,
                authorIds: Components.Schemas.BlogPostAuthorIdsField,
                tagIds: Components.Schemas.BlogPostTagIdsField,
                metadata: Components.Schemas.WebMetadataDetailSchema,
                createdAt: Swift.Double,
                updatedAt: Swift.Double
            ) {
                self.id = id
                self.title = title
                self.excerpt = excerpt
                self.content = content
                self.imageAssetId = imageAssetId
                self.authorIds = authorIds
                self.tagIds = tagIds
                self.metadata = metadata
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case title
                case excerpt
                case content
                case imageAssetId
                case authorIds
                case tagIds
                case metadata
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema`.
        public struct WebMetadataDetailSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/referenceType`.
            public var referenceType: Components.Schemas.AdminWebMetadataReferenceTypeField?
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/referenceId`.
            public var referenceId: Components.Schemas.AdminWebMetadataReferenceIDField?
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/slug`.
            public var slug: Swift.String
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/template`.
            public var template: Swift.String
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/publicationDate`.
            public var publicationDate: Swift.Double?
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/expirationDate`.
            public var expirationDate: Swift.Double?
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/status`.
            public var status: Swift.String
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/title`.
            public var title: Swift.String?
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/excerpt`.
            public var excerpt: Swift.String?
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/imageUrl`.
            public var imageUrl: Swift.String?
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/canonicalUrl`.
            public var canonicalUrl: Swift.String?
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/noIndex`.
            public var noIndex: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/primaryKeyword`.
            public var primaryKeyword: Swift.String
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/cssCodeInjection`.
            public var cssCodeInjection: Swift.String?
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/javascriptCodeInjection`.
            public var javascriptCodeInjection: Swift.String?
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/structuredDataCodeInjection`.
            public var structuredDataCodeInjection: Swift.String?
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/createdAt`.
            public var createdAt: Swift.Double
            /// - Remark: Generated from `#/components/schemas/WebMetadataDetailSchema/updatedAt`.
            public var updatedAt: Swift.Double
            /// Creates a new `WebMetadataDetailSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - referenceType:
            ///   - referenceId:
            ///   - slug:
            ///   - template:
            ///   - publicationDate:
            ///   - expirationDate:
            ///   - status:
            ///   - title:
            ///   - excerpt:
            ///   - imageUrl:
            ///   - canonicalUrl:
            ///   - noIndex:
            ///   - primaryKeyword:
            ///   - cssCodeInjection:
            ///   - javascriptCodeInjection:
            ///   - structuredDataCodeInjection:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Swift.String,
                referenceType: Components.Schemas.AdminWebMetadataReferenceTypeField? = nil,
                referenceId: Components.Schemas.AdminWebMetadataReferenceIDField? = nil,
                slug: Swift.String,
                template: Swift.String,
                publicationDate: Swift.Double? = nil,
                expirationDate: Swift.Double? = nil,
                status: Swift.String,
                title: Swift.String? = nil,
                excerpt: Swift.String? = nil,
                imageUrl: Swift.String? = nil,
                canonicalUrl: Swift.String? = nil,
                noIndex: Swift.Bool,
                primaryKeyword: Swift.String,
                cssCodeInjection: Swift.String? = nil,
                javascriptCodeInjection: Swift.String? = nil,
                structuredDataCodeInjection: Swift.String? = nil,
                createdAt: Swift.Double,
                updatedAt: Swift.Double
            ) {
                self.id = id
                self.referenceType = referenceType
                self.referenceId = referenceId
                self.slug = slug
                self.template = template
                self.publicationDate = publicationDate
                self.expirationDate = expirationDate
                self.status = status
                self.title = title
                self.excerpt = excerpt
                self.imageUrl = imageUrl
                self.canonicalUrl = canonicalUrl
                self.noIndex = noIndex
                self.primaryKeyword = primaryKeyword
                self.cssCodeInjection = cssCodeInjection
                self.javascriptCodeInjection = javascriptCodeInjection
                self.structuredDataCodeInjection = structuredDataCodeInjection
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case referenceType
                case referenceId
                case slug
                case template
                case publicationDate
                case expirationDate
                case status
                case title
                case excerpt
                case imageUrl
                case canonicalUrl
                case noIndex
                case primaryKeyword
                case cssCodeInjection
                case javascriptCodeInjection
                case structuredDataCodeInjection
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/AdminWebMetadataReferenceTypeField`.
        public typealias AdminWebMetadataReferenceTypeField = Swift.String
        /// - Remark: Generated from `#/components/schemas/AdminWebMetadataReferenceIDField`.
        public typealias AdminWebMetadataReferenceIDField = Swift.String
        /// - Remark: Generated from `#/components/schemas/DeleteRequestSchema`.
        public struct DeleteRequestSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/DeleteRequestSchema/ids`.
            public var ids: [Swift.String]
            /// - Remark: Generated from `#/components/schemas/DeleteRequestSchema/results`.
            public var results: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/DeleteRequestSchema/summary`.
            public var summary: Swift.Bool
            /// Creates a new `DeleteRequestSchema`.
            ///
            /// - Parameters:
            ///   - ids:
            ///   - results:
            ///   - summary:
            public init(
                ids: [Swift.String],
                results: Swift.Bool,
                summary: Swift.Bool
            ) {
                self.ids = ids
                self.results = results
                self.summary = summary
            }
            public enum CodingKeys: String, CodingKey {
                case ids
                case results
                case summary
            }
        }
        /// - Remark: Generated from `#/components/schemas/DeleteResponseSchema`.
        public struct DeleteResponseSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/DeleteResponseSchema/results`.
            public var results: Components.Schemas.DeleteResultListSchema?
            /// - Remark: Generated from `#/components/schemas/DeleteResponseSchema/summary`.
            public var summary: Components.Schemas.DeleteSummarySchema?
            /// Creates a new `DeleteResponseSchema`.
            ///
            /// - Parameters:
            ///   - results:
            ///   - summary:
            public init(
                results: Components.Schemas.DeleteResultListSchema? = nil,
                summary: Components.Schemas.DeleteSummarySchema? = nil
            ) {
                self.results = results
                self.summary = summary
            }
            public enum CodingKeys: String, CodingKey {
                case results
                case summary
            }
        }
        /// - Remark: Generated from `#/components/schemas/DeleteResultListSchema`.
        public struct DeleteResultListSchemaPayload: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/DeleteResultListSchema/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/DeleteResultListSchema/status`.
            @frozen public enum StatusPayload: String, Codable, Hashable, Sendable, CaseIterable {
                case deleted = "deleted"
                case notFound = "not_found"
                case forbidden = "forbidden"
            }
            /// - Remark: Generated from `#/components/schemas/DeleteResultListSchema/status`.
            public var status: Components.Schemas.DeleteResultListSchemaPayload.StatusPayload
            /// Creates a new `DeleteResultListSchemaPayload`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - status:
            public init(
                id: Swift.String,
                status: Components.Schemas.DeleteResultListSchemaPayload.StatusPayload
            ) {
                self.id = id
                self.status = status
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case status
            }
        }
        /// - Remark: Generated from `#/components/schemas/DeleteResultListSchema`.
        public typealias DeleteResultListSchema = [Components.Schemas.DeleteResultListSchemaPayload]
        /// - Remark: Generated from `#/components/schemas/DeleteSummarySchema`.
        public struct DeleteSummarySchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/DeleteSummarySchema/requested`.
            public var requested: Swift.Int
            /// - Remark: Generated from `#/components/schemas/DeleteSummarySchema/deleted`.
            public var deleted: Swift.Int
            /// - Remark: Generated from `#/components/schemas/DeleteSummarySchema/omitted`.
            public var omitted: Swift.Int
            /// Creates a new `DeleteSummarySchema`.
            ///
            /// - Parameters:
            ///   - requested:
            ///   - deleted:
            ///   - omitted:
            public init(
                requested: Swift.Int,
                deleted: Swift.Int,
                omitted: Swift.Int
            ) {
                self.requested = requested
                self.deleted = deleted
                self.omitted = omitted
            }
            public enum CodingKeys: String, CodingKey {
                case requested
                case deleted
                case omitted
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogPostListSchema`.
        public typealias BlogPostListSchema = [Components.Schemas.BlogPostListItemSchema]
        /// - Remark: Generated from `#/components/schemas/BlogPostListItemSchema`.
        public struct BlogPostListItemSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSchema/id`.
            public var id: Components.Schemas.BlogPostIdField
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSchema/title`.
            public var title: Components.Schemas.BlogPostTitleField
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSchema/excerpt`.
            public var excerpt: Components.Schemas.BlogPostExcerptField
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.BlogPostImageAssetIdField?
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSchema/createdAt`.
            public var createdAt: Components.Schemas.BlogPostCreatedAtField
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSchema/updatedAt`.
            public var updatedAt: Components.Schemas.BlogPostUpdatedAtField
            /// Creates a new `BlogPostListItemSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - title:
            ///   - excerpt:
            ///   - imageAssetId:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Components.Schemas.BlogPostIdField,
                title: Components.Schemas.BlogPostTitleField,
                excerpt: Components.Schemas.BlogPostExcerptField,
                imageAssetId: Components.Schemas.BlogPostImageAssetIdField? = nil,
                createdAt: Components.Schemas.BlogPostCreatedAtField,
                updatedAt: Components.Schemas.BlogPostUpdatedAtField
            ) {
                self.id = id
                self.title = title
                self.excerpt = excerpt
                self.imageAssetId = imageAssetId
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case title
                case excerpt
                case imageAssetId
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogPostIdField`.
        public typealias BlogPostIdField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogPostTitleField`.
        public typealias BlogPostTitleField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogPostExcerptField`.
        public typealias BlogPostExcerptField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogPostCreatedAtField`.
        public typealias BlogPostCreatedAtField = Swift.Double
        /// - Remark: Generated from `#/components/schemas/BlogPostUpdatedAtField`.
        public typealias BlogPostUpdatedAtField = Swift.Double
        /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchQuerySchema`.
        public struct BlogPostListItemSearchQuerySchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchQuerySchema/page`.
            public var page: Components.Schemas.SearchPageSchema
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchQuerySchema/SortPayload`.
            public struct SortPayloadPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchQuerySchema/SortPayload/field`.
                @frozen public enum FieldPayload: String, Codable, Hashable, Sendable, CaseIterable {
                    case id = "id"
                    case title = "title"
                    case createdAt = "createdAt"
                    case updatedAt = "updatedAt"
                }
                /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchQuerySchema/SortPayload/field`.
                public var field: Components.Schemas.BlogPostListItemSearchQuerySchema.SortPayloadPayload.FieldPayload
                /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchQuerySchema/SortPayload/direction`.
                public var direction: Components.Schemas.SortDirection
                /// Creates a new `SortPayloadPayload`.
                ///
                /// - Parameters:
                ///   - field:
                ///   - direction:
                public init(
                    field: Components.Schemas.BlogPostListItemSearchQuerySchema.SortPayloadPayload.FieldPayload,
                    direction: Components.Schemas.SortDirection
                ) {
                    self.field = field
                    self.direction = direction
                }
                public enum CodingKeys: String, CodingKey {
                    case field
                    case direction
                }
            }
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchQuerySchema/sort`.
            public typealias SortPayload = [Components.Schemas.BlogPostListItemSearchQuerySchema.SortPayloadPayload]
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchQuerySchema/sort`.
            public var sort: Components.Schemas.BlogPostListItemSearchQuerySchema.SortPayload?
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchQuerySchema/filters`.
            public struct FiltersPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchQuerySchema/filters/search`.
                public var search: Components.Schemas.SearchStringField?
                /// Creates a new `FiltersPayload`.
                ///
                /// - Parameters:
                ///   - search:
                public init(search: Components.Schemas.SearchStringField? = nil) {
                    self.search = search
                }
                public enum CodingKeys: String, CodingKey {
                    case search
                }
            }
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchQuerySchema/filters`.
            public var filters: Components.Schemas.BlogPostListItemSearchQuerySchema.FiltersPayload
            /// Creates a new `BlogPostListItemSearchQuerySchema`.
            ///
            /// - Parameters:
            ///   - page:
            ///   - sort:
            ///   - filters:
            public init(
                page: Components.Schemas.SearchPageSchema,
                sort: Components.Schemas.BlogPostListItemSearchQuerySchema.SortPayload? = nil,
                filters: Components.Schemas.BlogPostListItemSearchQuerySchema.FiltersPayload
            ) {
                self.page = page
                self.sort = sort
                self.filters = filters
            }
            public enum CodingKeys: String, CodingKey {
                case page
                case sort
                case filters
            }
        }
        /// - Remark: Generated from `#/components/schemas/SearchPageSchema`.
        public struct SearchPageSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SearchPageSchema/size`.
            public var size: Components.Schemas.SearchPageSizeField
            /// - Remark: Generated from `#/components/schemas/SearchPageSchema/number`.
            public var number: Components.Schemas.SearchPageNumberField
            /// Creates a new `SearchPageSchema`.
            ///
            /// - Parameters:
            ///   - size:
            ///   - number:
            public init(
                size: Components.Schemas.SearchPageSizeField,
                number: Components.Schemas.SearchPageNumberField
            ) {
                self.size = size
                self.number = number
            }
            public enum CodingKeys: String, CodingKey {
                case size
                case number
            }
        }
        /// - Remark: Generated from `#/components/schemas/SearchPageSizeField`.
        public typealias SearchPageSizeField = Swift.Int
        /// - Remark: Generated from `#/components/schemas/SearchPageNumberField`.
        public typealias SearchPageNumberField = Swift.Int
        /// - Remark: Generated from `#/components/schemas/SortDirection`.
        @frozen public enum SortDirection: String, Codable, Hashable, Sendable, CaseIterable {
            case asc = "asc"
            case desc = "desc"
        }
        /// - Remark: Generated from `#/components/schemas/SearchStringField`.
        public typealias SearchStringField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchSchema`.
        public struct BlogPostListItemSearchSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchSchema/query`.
            public var query: Components.Schemas.BlogPostListItemSearchQuerySchema
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchSchema/data`.
            public struct DataPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchSchema/data/items`.
                public var items: [Components.Schemas.BlogPostListItemSchema]
                /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchSchema/data/total`.
                public var total: Swift.Int
                /// Creates a new `DataPayload`.
                ///
                /// - Parameters:
                ///   - items:
                ///   - total:
                public init(
                    items: [Components.Schemas.BlogPostListItemSchema],
                    total: Swift.Int
                ) {
                    self.items = items
                    self.total = total
                }
                public enum CodingKeys: String, CodingKey {
                    case items
                    case total
                }
            }
            /// - Remark: Generated from `#/components/schemas/BlogPostListItemSearchSchema/data`.
            public var data: Components.Schemas.BlogPostListItemSearchSchema.DataPayload
            /// Creates a new `BlogPostListItemSearchSchema`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - data:
            public init(
                query: Components.Schemas.BlogPostListItemSearchQuerySchema,
                data: Components.Schemas.BlogPostListItemSearchSchema.DataPayload
            ) {
                self.query = query
                self.data = data
            }
            public enum CodingKeys: String, CodingKey {
                case query
                case data
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogPostPatchSchema`.
        public struct BlogPostPatchSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogPostPatchSchema/title`.
            public var title: Components.Schemas.BlogPostTitleField?
            /// - Remark: Generated from `#/components/schemas/BlogPostPatchSchema/excerpt`.
            public var excerpt: Components.Schemas.BlogPostExcerptField?
            /// - Remark: Generated from `#/components/schemas/BlogPostPatchSchema/content`.
            public var content: Components.Schemas.BlogPostContentField?
            /// - Remark: Generated from `#/components/schemas/BlogPostPatchSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.BlogPostImageAssetIdField?
            /// - Remark: Generated from `#/components/schemas/BlogPostPatchSchema/authorIds`.
            public var authorIds: Components.Schemas.BlogPostAuthorIdsField?
            /// - Remark: Generated from `#/components/schemas/BlogPostPatchSchema/tagIds`.
            public var tagIds: Components.Schemas.BlogPostTagIdsField?
            /// Creates a new `BlogPostPatchSchema`.
            ///
            /// - Parameters:
            ///   - title:
            ///   - excerpt:
            ///   - content:
            ///   - imageAssetId:
            ///   - authorIds:
            ///   - tagIds:
            public init(
                title: Components.Schemas.BlogPostTitleField? = nil,
                excerpt: Components.Schemas.BlogPostExcerptField? = nil,
                content: Components.Schemas.BlogPostContentField? = nil,
                imageAssetId: Components.Schemas.BlogPostImageAssetIdField? = nil,
                authorIds: Components.Schemas.BlogPostAuthorIdsField? = nil,
                tagIds: Components.Schemas.BlogPostTagIdsField? = nil
            ) {
                self.title = title
                self.excerpt = excerpt
                self.content = content
                self.imageAssetId = imageAssetId
                self.authorIds = authorIds
                self.tagIds = tagIds
            }
            public enum CodingKeys: String, CodingKey {
                case title
                case excerpt
                case content
                case imageAssetId
                case authorIds
                case tagIds
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogPostContentField`.
        public typealias BlogPostContentField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogAuthorCreateSchema`.
        public struct BlogAuthorCreateSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogAuthorCreateSchema/name`.
            public var name: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorCreateSchema/excerpt`.
            public var excerpt: Components.Schemas.BlogAuthorExcerptField?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorCreateSchema/content`.
            public var content: Components.Schemas.BlogAuthorContentField?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorCreateSchema/profileImageAssetId`.
            public var profileImageAssetId: Components.Schemas.BlogAuthorProfileImageAssetIdField?
            /// Creates a new `BlogAuthorCreateSchema`.
            ///
            /// - Parameters:
            ///   - name:
            ///   - excerpt:
            ///   - content:
            ///   - profileImageAssetId:
            public init(
                name: Swift.String,
                excerpt: Components.Schemas.BlogAuthorExcerptField? = nil,
                content: Components.Schemas.BlogAuthorContentField? = nil,
                profileImageAssetId: Components.Schemas.BlogAuthorProfileImageAssetIdField? = nil
            ) {
                self.name = name
                self.excerpt = excerpt
                self.content = content
                self.profileImageAssetId = profileImageAssetId
            }
            public enum CodingKeys: String, CodingKey {
                case name
                case excerpt
                case content
                case profileImageAssetId
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogAuthorExcerptField`.
        public typealias BlogAuthorExcerptField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogAuthorContentField`.
        public typealias BlogAuthorContentField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogAuthorProfileImageAssetIdField`.
        public typealias BlogAuthorProfileImageAssetIdField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogAuthorDetailSchema`.
        public struct BlogAuthorDetailSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogAuthorDetailSchema/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorDetailSchema/name`.
            public var name: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorDetailSchema/excerpt`.
            public var excerpt: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorDetailSchema/content`.
            public var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorDetailSchema/profileImageAssetId`.
            public var profileImageAssetId: Components.Schemas.BlogAuthorProfileImageAssetIdField?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorDetailSchema/metadata`.
            public var metadata: Components.Schemas.WebMetadataDetailSchema
            /// - Remark: Generated from `#/components/schemas/BlogAuthorDetailSchema/createdAt`.
            public var createdAt: Swift.Double
            /// - Remark: Generated from `#/components/schemas/BlogAuthorDetailSchema/updatedAt`.
            public var updatedAt: Swift.Double
            /// Creates a new `BlogAuthorDetailSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - name:
            ///   - excerpt:
            ///   - content:
            ///   - profileImageAssetId:
            ///   - metadata:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Swift.String,
                name: Swift.String,
                excerpt: Swift.String,
                content: Swift.String,
                profileImageAssetId: Components.Schemas.BlogAuthorProfileImageAssetIdField? = nil,
                metadata: Components.Schemas.WebMetadataDetailSchema,
                createdAt: Swift.Double,
                updatedAt: Swift.Double
            ) {
                self.id = id
                self.name = name
                self.excerpt = excerpt
                self.content = content
                self.profileImageAssetId = profileImageAssetId
                self.metadata = metadata
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case name
                case excerpt
                case content
                case profileImageAssetId
                case metadata
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogAuthorListSchema`.
        public typealias BlogAuthorListSchema = [Components.Schemas.BlogAuthorListItemSchema]
        /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSchema`.
        public struct BlogAuthorListItemSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSchema/id`.
            public var id: Components.Schemas.BlogAuthorIdField
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSchema/name`.
            public var name: Components.Schemas.BlogAuthorNameField
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSchema/excerpt`.
            public var excerpt: Components.Schemas.BlogAuthorExcerptField
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSchema/profileImageAssetId`.
            public var profileImageAssetId: Components.Schemas.BlogAuthorProfileImageAssetIdField?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSchema/createdAt`.
            public var createdAt: Components.Schemas.BlogAuthorCreatedAtField
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSchema/updatedAt`.
            public var updatedAt: Components.Schemas.BlogAuthorUpdatedAtField
            /// Creates a new `BlogAuthorListItemSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - name:
            ///   - excerpt:
            ///   - profileImageAssetId:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Components.Schemas.BlogAuthorIdField,
                name: Components.Schemas.BlogAuthorNameField,
                excerpt: Components.Schemas.BlogAuthorExcerptField,
                profileImageAssetId: Components.Schemas.BlogAuthorProfileImageAssetIdField? = nil,
                createdAt: Components.Schemas.BlogAuthorCreatedAtField,
                updatedAt: Components.Schemas.BlogAuthorUpdatedAtField
            ) {
                self.id = id
                self.name = name
                self.excerpt = excerpt
                self.profileImageAssetId = profileImageAssetId
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case name
                case excerpt
                case profileImageAssetId
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogAuthorNameField`.
        public typealias BlogAuthorNameField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogAuthorCreatedAtField`.
        public typealias BlogAuthorCreatedAtField = Swift.Double
        /// - Remark: Generated from `#/components/schemas/BlogAuthorUpdatedAtField`.
        public typealias BlogAuthorUpdatedAtField = Swift.Double
        /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchQuerySchema`.
        public struct BlogAuthorListItemSearchQuerySchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchQuerySchema/page`.
            public var page: Components.Schemas.SearchPageSchema
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchQuerySchema/SortPayload`.
            public struct SortPayloadPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchQuerySchema/SortPayload/field`.
                @frozen public enum FieldPayload: String, Codable, Hashable, Sendable, CaseIterable {
                    case id = "id"
                    case key = "key"
                    case name = "name"
                    case createdAt = "createdAt"
                    case updatedAt = "updatedAt"
                }
                /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchQuerySchema/SortPayload/field`.
                public var field: Components.Schemas.BlogAuthorListItemSearchQuerySchema.SortPayloadPayload.FieldPayload
                /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchQuerySchema/SortPayload/direction`.
                public var direction: Components.Schemas.SortDirection
                /// Creates a new `SortPayloadPayload`.
                ///
                /// - Parameters:
                ///   - field:
                ///   - direction:
                public init(
                    field: Components.Schemas.BlogAuthorListItemSearchQuerySchema.SortPayloadPayload.FieldPayload,
                    direction: Components.Schemas.SortDirection
                ) {
                    self.field = field
                    self.direction = direction
                }
                public enum CodingKeys: String, CodingKey {
                    case field
                    case direction
                }
            }
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchQuerySchema/sort`.
            public typealias SortPayload = [Components.Schemas.BlogAuthorListItemSearchQuerySchema.SortPayloadPayload]
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchQuerySchema/sort`.
            public var sort: Components.Schemas.BlogAuthorListItemSearchQuerySchema.SortPayload?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchQuerySchema/filters`.
            public struct FiltersPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchQuerySchema/filters/search`.
                public var search: Components.Schemas.SearchStringField?
                /// Creates a new `FiltersPayload`.
                ///
                /// - Parameters:
                ///   - search:
                public init(search: Components.Schemas.SearchStringField? = nil) {
                    self.search = search
                }
                public enum CodingKeys: String, CodingKey {
                    case search
                }
            }
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchQuerySchema/filters`.
            public var filters: Components.Schemas.BlogAuthorListItemSearchQuerySchema.FiltersPayload
            /// Creates a new `BlogAuthorListItemSearchQuerySchema`.
            ///
            /// - Parameters:
            ///   - page:
            ///   - sort:
            ///   - filters:
            public init(
                page: Components.Schemas.SearchPageSchema,
                sort: Components.Schemas.BlogAuthorListItemSearchQuerySchema.SortPayload? = nil,
                filters: Components.Schemas.BlogAuthorListItemSearchQuerySchema.FiltersPayload
            ) {
                self.page = page
                self.sort = sort
                self.filters = filters
            }
            public enum CodingKeys: String, CodingKey {
                case page
                case sort
                case filters
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchSchema`.
        public struct BlogAuthorListItemSearchSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchSchema/query`.
            public var query: Components.Schemas.BlogAuthorListItemSearchQuerySchema
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchSchema/data`.
            public struct DataPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchSchema/data/items`.
                public var items: [Components.Schemas.BlogAuthorListItemSchema]
                /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchSchema/data/total`.
                public var total: Swift.Int
                /// Creates a new `DataPayload`.
                ///
                /// - Parameters:
                ///   - items:
                ///   - total:
                public init(
                    items: [Components.Schemas.BlogAuthorListItemSchema],
                    total: Swift.Int
                ) {
                    self.items = items
                    self.total = total
                }
                public enum CodingKeys: String, CodingKey {
                    case items
                    case total
                }
            }
            /// - Remark: Generated from `#/components/schemas/BlogAuthorListItemSearchSchema/data`.
            public var data: Components.Schemas.BlogAuthorListItemSearchSchema.DataPayload
            /// Creates a new `BlogAuthorListItemSearchSchema`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - data:
            public init(
                query: Components.Schemas.BlogAuthorListItemSearchQuerySchema,
                data: Components.Schemas.BlogAuthorListItemSearchSchema.DataPayload
            ) {
                self.query = query
                self.data = data
            }
            public enum CodingKeys: String, CodingKey {
                case query
                case data
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogAuthorPatchSchema`.
        public struct BlogAuthorPatchSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogAuthorPatchSchema/name`.
            public var name: Components.Schemas.BlogAuthorNameField?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorPatchSchema/excerpt`.
            public var excerpt: Components.Schemas.BlogAuthorExcerptField?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorPatchSchema/content`.
            public var content: Components.Schemas.BlogAuthorContentField?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorPatchSchema/profileImageAssetId`.
            public var profileImageAssetId: Components.Schemas.BlogAuthorProfileImageAssetIdField?
            /// Creates a new `BlogAuthorPatchSchema`.
            ///
            /// - Parameters:
            ///   - name:
            ///   - excerpt:
            ///   - content:
            ///   - profileImageAssetId:
            public init(
                name: Components.Schemas.BlogAuthorNameField? = nil,
                excerpt: Components.Schemas.BlogAuthorExcerptField? = nil,
                content: Components.Schemas.BlogAuthorContentField? = nil,
                profileImageAssetId: Components.Schemas.BlogAuthorProfileImageAssetIdField? = nil
            ) {
                self.name = name
                self.excerpt = excerpt
                self.content = content
                self.profileImageAssetId = profileImageAssetId
            }
            public enum CodingKeys: String, CodingKey {
                case name
                case excerpt
                case content
                case profileImageAssetId
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkCreateSchema`.
        public struct BlogAuthorLinkCreateSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkCreateSchema/label`.
            public var label: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkCreateSchema/url`.
            public var url: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkCreateSchema/priority`.
            public var priority: Swift.Int
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkCreateSchema/isBlank`.
            public var isBlank: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkCreateSchema/permission`.
            public var permission: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkCreateSchema/notes`.
            public var notes: Components.Schemas.BlogAuthorLinkNotesField?
            /// Creates a new `BlogAuthorLinkCreateSchema`.
            ///
            /// - Parameters:
            ///   - label:
            ///   - url:
            ///   - priority:
            ///   - isBlank:
            ///   - permission:
            ///   - notes:
            public init(
                label: Swift.String,
                url: Swift.String,
                priority: Swift.Int,
                isBlank: Swift.Bool,
                permission: Swift.String,
                notes: Components.Schemas.BlogAuthorLinkNotesField? = nil
            ) {
                self.label = label
                self.url = url
                self.priority = priority
                self.isBlank = isBlank
                self.permission = permission
                self.notes = notes
            }
            public enum CodingKeys: String, CodingKey {
                case label
                case url
                case priority
                case isBlank
                case permission
                case notes
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkNotesField`.
        public typealias BlogAuthorLinkNotesField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkDetailSchema`.
        public struct BlogAuthorLinkDetailSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkDetailSchema/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkDetailSchema/menuId`.
            public var menuId: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkDetailSchema/label`.
            public var label: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkDetailSchema/url`.
            public var url: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkDetailSchema/priority`.
            public var priority: Swift.Int
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkDetailSchema/isBlank`.
            public var isBlank: Swift.Bool
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkDetailSchema/permission`.
            public var permission: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkDetailSchema/notes`.
            public var notes: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkDetailSchema/createdAt`.
            public var createdAt: Swift.Double
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkDetailSchema/updatedAt`.
            public var updatedAt: Swift.Double
            /// Creates a new `BlogAuthorLinkDetailSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - menuId:
            ///   - label:
            ///   - url:
            ///   - priority:
            ///   - isBlank:
            ///   - permission:
            ///   - notes:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Swift.String,
                menuId: Swift.String,
                label: Swift.String,
                url: Swift.String,
                priority: Swift.Int,
                isBlank: Swift.Bool,
                permission: Swift.String,
                notes: Swift.String,
                createdAt: Swift.Double,
                updatedAt: Swift.Double
            ) {
                self.id = id
                self.menuId = menuId
                self.label = label
                self.url = url
                self.priority = priority
                self.isBlank = isBlank
                self.permission = permission
                self.notes = notes
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case menuId
                case label
                case url
                case priority
                case isBlank
                case permission
                case notes
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListSchema`.
        public typealias BlogAuthorLinkListSchema = [Components.Schemas.BlogAuthorLinkListItemSchema]
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSchema`.
        public struct BlogAuthorLinkListItemSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSchema/id`.
            public var id: Components.Schemas.BlogAuthorLinkIdField
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSchema/menuId`.
            public var menuId: Components.Schemas.BlogAuthorIdField
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSchema/label`.
            public var label: Components.Schemas.BlogAuthorLinkLabelField
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSchema/url`.
            public var url: Components.Schemas.BlogAuthorLinkURLField
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSchema/priority`.
            public var priority: Components.Schemas.BlogAuthorLinkPriorityField
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSchema/isBlank`.
            public var isBlank: Components.Schemas.BlogAuthorLinkIsBlankField
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSchema/permission`.
            public var permission: Components.Schemas.BlogAuthorLinkPermissionField
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSchema/createdAt`.
            public var createdAt: Components.Schemas.BlogAuthorLinkCreatedAtField
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSchema/updatedAt`.
            public var updatedAt: Components.Schemas.BlogAuthorLinkUpdatedAtField
            /// Creates a new `BlogAuthorLinkListItemSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - menuId:
            ///   - label:
            ///   - url:
            ///   - priority:
            ///   - isBlank:
            ///   - permission:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Components.Schemas.BlogAuthorLinkIdField,
                menuId: Components.Schemas.BlogAuthorIdField,
                label: Components.Schemas.BlogAuthorLinkLabelField,
                url: Components.Schemas.BlogAuthorLinkURLField,
                priority: Components.Schemas.BlogAuthorLinkPriorityField,
                isBlank: Components.Schemas.BlogAuthorLinkIsBlankField,
                permission: Components.Schemas.BlogAuthorLinkPermissionField,
                createdAt: Components.Schemas.BlogAuthorLinkCreatedAtField,
                updatedAt: Components.Schemas.BlogAuthorLinkUpdatedAtField
            ) {
                self.id = id
                self.menuId = menuId
                self.label = label
                self.url = url
                self.priority = priority
                self.isBlank = isBlank
                self.permission = permission
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case menuId
                case label
                case url
                case priority
                case isBlank
                case permission
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkIdField`.
        public typealias BlogAuthorLinkIdField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkLabelField`.
        public typealias BlogAuthorLinkLabelField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkURLField`.
        public typealias BlogAuthorLinkURLField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkPriorityField`.
        public typealias BlogAuthorLinkPriorityField = Swift.Int
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkIsBlankField`.
        public typealias BlogAuthorLinkIsBlankField = Swift.Bool
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkPermissionField`.
        public typealias BlogAuthorLinkPermissionField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkCreatedAtField`.
        public typealias BlogAuthorLinkCreatedAtField = Swift.Double
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkUpdatedAtField`.
        public typealias BlogAuthorLinkUpdatedAtField = Swift.Double
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchQuerySchema`.
        public struct BlogAuthorLinkListItemSearchQuerySchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchQuerySchema/page`.
            public var page: Components.Schemas.SearchPageSchema
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchQuerySchema/SortPayload`.
            public struct SortPayloadPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchQuerySchema/SortPayload/field`.
                @frozen public enum FieldPayload: String, Codable, Hashable, Sendable, CaseIterable {
                    case id = "id"
                    case label = "label"
                    case url = "url"
                    case priority = "priority"
                    case permission = "permission"
                    case createdAt = "createdAt"
                    case updatedAt = "updatedAt"
                }
                /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchQuerySchema/SortPayload/field`.
                public var field: Components.Schemas.BlogAuthorLinkListItemSearchQuerySchema.SortPayloadPayload.FieldPayload
                /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchQuerySchema/SortPayload/direction`.
                public var direction: Components.Schemas.SortDirection
                /// Creates a new `SortPayloadPayload`.
                ///
                /// - Parameters:
                ///   - field:
                ///   - direction:
                public init(
                    field: Components.Schemas.BlogAuthorLinkListItemSearchQuerySchema.SortPayloadPayload.FieldPayload,
                    direction: Components.Schemas.SortDirection
                ) {
                    self.field = field
                    self.direction = direction
                }
                public enum CodingKeys: String, CodingKey {
                    case field
                    case direction
                }
            }
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchQuerySchema/sort`.
            public typealias SortPayload = [Components.Schemas.BlogAuthorLinkListItemSearchQuerySchema.SortPayloadPayload]
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchQuerySchema/sort`.
            public var sort: Components.Schemas.BlogAuthorLinkListItemSearchQuerySchema.SortPayload?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchQuerySchema/filters`.
            public struct FiltersPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchQuerySchema/filters/search`.
                public var search: Components.Schemas.SearchStringField?
                /// Creates a new `FiltersPayload`.
                ///
                /// - Parameters:
                ///   - search:
                public init(search: Components.Schemas.SearchStringField? = nil) {
                    self.search = search
                }
                public enum CodingKeys: String, CodingKey {
                    case search
                }
            }
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchQuerySchema/filters`.
            public var filters: Components.Schemas.BlogAuthorLinkListItemSearchQuerySchema.FiltersPayload
            /// Creates a new `BlogAuthorLinkListItemSearchQuerySchema`.
            ///
            /// - Parameters:
            ///   - page:
            ///   - sort:
            ///   - filters:
            public init(
                page: Components.Schemas.SearchPageSchema,
                sort: Components.Schemas.BlogAuthorLinkListItemSearchQuerySchema.SortPayload? = nil,
                filters: Components.Schemas.BlogAuthorLinkListItemSearchQuerySchema.FiltersPayload
            ) {
                self.page = page
                self.sort = sort
                self.filters = filters
            }
            public enum CodingKeys: String, CodingKey {
                case page
                case sort
                case filters
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchSchema`.
        public struct BlogAuthorLinkListItemSearchSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchSchema/query`.
            public var query: Components.Schemas.BlogAuthorLinkListItemSearchQuerySchema
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchSchema/data`.
            public struct DataPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchSchema/data/items`.
                public var items: [Components.Schemas.BlogAuthorLinkListItemSchema]
                /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchSchema/data/total`.
                public var total: Swift.Int
                /// Creates a new `DataPayload`.
                ///
                /// - Parameters:
                ///   - items:
                ///   - total:
                public init(
                    items: [Components.Schemas.BlogAuthorLinkListItemSchema],
                    total: Swift.Int
                ) {
                    self.items = items
                    self.total = total
                }
                public enum CodingKeys: String, CodingKey {
                    case items
                    case total
                }
            }
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkListItemSearchSchema/data`.
            public var data: Components.Schemas.BlogAuthorLinkListItemSearchSchema.DataPayload
            /// Creates a new `BlogAuthorLinkListItemSearchSchema`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - data:
            public init(
                query: Components.Schemas.BlogAuthorLinkListItemSearchQuerySchema,
                data: Components.Schemas.BlogAuthorLinkListItemSearchSchema.DataPayload
            ) {
                self.query = query
                self.data = data
            }
            public enum CodingKeys: String, CodingKey {
                case query
                case data
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkPatchSchema`.
        public struct BlogAuthorLinkPatchSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkPatchSchema/label`.
            public var label: Components.Schemas.BlogAuthorLinkLabelField?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkPatchSchema/url`.
            public var url: Components.Schemas.BlogAuthorLinkURLField?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkPatchSchema/priority`.
            public var priority: Components.Schemas.BlogAuthorLinkPriorityField?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkPatchSchema/isBlank`.
            public var isBlank: Components.Schemas.BlogAuthorLinkIsBlankField?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkPatchSchema/permission`.
            public var permission: Components.Schemas.BlogAuthorLinkPermissionField?
            /// - Remark: Generated from `#/components/schemas/BlogAuthorLinkPatchSchema/notes`.
            public var notes: Components.Schemas.BlogAuthorLinkNotesField?
            /// Creates a new `BlogAuthorLinkPatchSchema`.
            ///
            /// - Parameters:
            ///   - label:
            ///   - url:
            ///   - priority:
            ///   - isBlank:
            ///   - permission:
            ///   - notes:
            public init(
                label: Components.Schemas.BlogAuthorLinkLabelField? = nil,
                url: Components.Schemas.BlogAuthorLinkURLField? = nil,
                priority: Components.Schemas.BlogAuthorLinkPriorityField? = nil,
                isBlank: Components.Schemas.BlogAuthorLinkIsBlankField? = nil,
                permission: Components.Schemas.BlogAuthorLinkPermissionField? = nil,
                notes: Components.Schemas.BlogAuthorLinkNotesField? = nil
            ) {
                self.label = label
                self.url = url
                self.priority = priority
                self.isBlank = isBlank
                self.permission = permission
                self.notes = notes
            }
            public enum CodingKeys: String, CodingKey {
                case label
                case url
                case priority
                case isBlank
                case permission
                case notes
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogSettingsDetailSchema`.
        public struct BlogSettingsDetailSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogSettingsDetailSchema/postListPath`.
            public var postListPath: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogSettingsDetailSchema/authorListPath`.
            public var authorListPath: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogSettingsDetailSchema/tagListPath`.
            public var tagListPath: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogSettingsDetailSchema/postPathPrefix`.
            public var postPathPrefix: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogSettingsDetailSchema/authorPathPrefix`.
            public var authorPathPrefix: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogSettingsDetailSchema/tagPathPrefix`.
            public var tagPathPrefix: Swift.String
            /// Creates a new `BlogSettingsDetailSchema`.
            ///
            /// - Parameters:
            ///   - postListPath:
            ///   - authorListPath:
            ///   - tagListPath:
            ///   - postPathPrefix:
            ///   - authorPathPrefix:
            ///   - tagPathPrefix:
            public init(
                postListPath: Swift.String,
                authorListPath: Swift.String,
                tagListPath: Swift.String,
                postPathPrefix: Swift.String,
                authorPathPrefix: Swift.String,
                tagPathPrefix: Swift.String
            ) {
                self.postListPath = postListPath
                self.authorListPath = authorListPath
                self.tagListPath = tagListPath
                self.postPathPrefix = postPathPrefix
                self.authorPathPrefix = authorPathPrefix
                self.tagPathPrefix = tagPathPrefix
            }
            public enum CodingKeys: String, CodingKey {
                case postListPath
                case authorListPath
                case tagListPath
                case postPathPrefix
                case authorPathPrefix
                case tagPathPrefix
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogSettingsUpdateSchema`.
        public struct BlogSettingsUpdateSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogSettingsUpdateSchema/postListPath`.
            public var postListPath: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogSettingsUpdateSchema/authorListPath`.
            public var authorListPath: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogSettingsUpdateSchema/tagListPath`.
            public var tagListPath: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogSettingsUpdateSchema/postPathPrefix`.
            public var postPathPrefix: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogSettingsUpdateSchema/authorPathPrefix`.
            public var authorPathPrefix: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogSettingsUpdateSchema/tagPathPrefix`.
            public var tagPathPrefix: Swift.String
            /// Creates a new `BlogSettingsUpdateSchema`.
            ///
            /// - Parameters:
            ///   - postListPath:
            ///   - authorListPath:
            ///   - tagListPath:
            ///   - postPathPrefix:
            ///   - authorPathPrefix:
            ///   - tagPathPrefix:
            public init(
                postListPath: Swift.String,
                authorListPath: Swift.String,
                tagListPath: Swift.String,
                postPathPrefix: Swift.String,
                authorPathPrefix: Swift.String,
                tagPathPrefix: Swift.String
            ) {
                self.postListPath = postListPath
                self.authorListPath = authorListPath
                self.tagListPath = tagListPath
                self.postPathPrefix = postPathPrefix
                self.authorPathPrefix = authorPathPrefix
                self.tagPathPrefix = tagPathPrefix
            }
            public enum CodingKeys: String, CodingKey {
                case postListPath
                case authorListPath
                case tagListPath
                case postPathPrefix
                case authorPathPrefix
                case tagPathPrefix
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogTagCreateSchema`.
        public struct BlogTagCreateSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogTagCreateSchema/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogTagCreateSchema/excerpt`.
            public var excerpt: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogTagCreateSchema/content`.
            public var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogTagCreateSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.BlogTagImageAssetIdField?
            /// Creates a new `BlogTagCreateSchema`.
            ///
            /// - Parameters:
            ///   - title:
            ///   - excerpt:
            ///   - content:
            ///   - imageAssetId:
            public init(
                title: Swift.String,
                excerpt: Swift.String,
                content: Swift.String,
                imageAssetId: Components.Schemas.BlogTagImageAssetIdField? = nil
            ) {
                self.title = title
                self.excerpt = excerpt
                self.content = content
                self.imageAssetId = imageAssetId
            }
            public enum CodingKeys: String, CodingKey {
                case title
                case excerpt
                case content
                case imageAssetId
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogTagImageAssetIdField`.
        public typealias BlogTagImageAssetIdField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogTagDetailSchema`.
        public struct BlogTagDetailSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogTagDetailSchema/id`.
            public var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogTagDetailSchema/title`.
            public var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogTagDetailSchema/excerpt`.
            public var excerpt: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogTagDetailSchema/content`.
            public var content: Swift.String
            /// - Remark: Generated from `#/components/schemas/BlogTagDetailSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.BlogTagImageAssetIdField?
            /// - Remark: Generated from `#/components/schemas/BlogTagDetailSchema/metadata`.
            public var metadata: Components.Schemas.WebMetadataDetailSchema
            /// - Remark: Generated from `#/components/schemas/BlogTagDetailSchema/createdAt`.
            public var createdAt: Swift.Double
            /// - Remark: Generated from `#/components/schemas/BlogTagDetailSchema/updatedAt`.
            public var updatedAt: Swift.Double
            /// Creates a new `BlogTagDetailSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - title:
            ///   - excerpt:
            ///   - content:
            ///   - imageAssetId:
            ///   - metadata:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Swift.String,
                title: Swift.String,
                excerpt: Swift.String,
                content: Swift.String,
                imageAssetId: Components.Schemas.BlogTagImageAssetIdField? = nil,
                metadata: Components.Schemas.WebMetadataDetailSchema,
                createdAt: Swift.Double,
                updatedAt: Swift.Double
            ) {
                self.id = id
                self.title = title
                self.excerpt = excerpt
                self.content = content
                self.imageAssetId = imageAssetId
                self.metadata = metadata
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case title
                case excerpt
                case content
                case imageAssetId
                case metadata
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogTagListSchema`.
        public typealias BlogTagListSchema = [Components.Schemas.BlogTagListItemSchema]
        /// - Remark: Generated from `#/components/schemas/BlogTagListItemSchema`.
        public struct BlogTagListItemSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSchema/id`.
            public var id: Components.Schemas.BlogTagIdField
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSchema/title`.
            public var title: Components.Schemas.BlogTagTitleField
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSchema/excerpt`.
            public var excerpt: Components.Schemas.BlogTagExcerptField
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.BlogTagImageAssetIdField?
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSchema/createdAt`.
            public var createdAt: Components.Schemas.BlogTagCreatedAtField
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSchema/updatedAt`.
            public var updatedAt: Components.Schemas.BlogTagUpdatedAtField
            /// Creates a new `BlogTagListItemSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - title:
            ///   - excerpt:
            ///   - imageAssetId:
            ///   - createdAt:
            ///   - updatedAt:
            public init(
                id: Components.Schemas.BlogTagIdField,
                title: Components.Schemas.BlogTagTitleField,
                excerpt: Components.Schemas.BlogTagExcerptField,
                imageAssetId: Components.Schemas.BlogTagImageAssetIdField? = nil,
                createdAt: Components.Schemas.BlogTagCreatedAtField,
                updatedAt: Components.Schemas.BlogTagUpdatedAtField
            ) {
                self.id = id
                self.title = title
                self.excerpt = excerpt
                self.imageAssetId = imageAssetId
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case title
                case excerpt
                case imageAssetId
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogTagTitleField`.
        public typealias BlogTagTitleField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogTagExcerptField`.
        public typealias BlogTagExcerptField = Swift.String
        /// - Remark: Generated from `#/components/schemas/BlogTagCreatedAtField`.
        public typealias BlogTagCreatedAtField = Swift.Double
        /// - Remark: Generated from `#/components/schemas/BlogTagUpdatedAtField`.
        public typealias BlogTagUpdatedAtField = Swift.Double
        /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchQuerySchema`.
        public struct BlogTagListItemSearchQuerySchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchQuerySchema/page`.
            public var page: Components.Schemas.SearchPageSchema
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchQuerySchema/SortPayload`.
            public struct SortPayloadPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchQuerySchema/SortPayload/field`.
                @frozen public enum FieldPayload: String, Codable, Hashable, Sendable, CaseIterable {
                    case id = "id"
                    case title = "title"
                    case createdAt = "createdAt"
                    case updatedAt = "updatedAt"
                }
                /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchQuerySchema/SortPayload/field`.
                public var field: Components.Schemas.BlogTagListItemSearchQuerySchema.SortPayloadPayload.FieldPayload
                /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchQuerySchema/SortPayload/direction`.
                public var direction: Components.Schemas.SortDirection
                /// Creates a new `SortPayloadPayload`.
                ///
                /// - Parameters:
                ///   - field:
                ///   - direction:
                public init(
                    field: Components.Schemas.BlogTagListItemSearchQuerySchema.SortPayloadPayload.FieldPayload,
                    direction: Components.Schemas.SortDirection
                ) {
                    self.field = field
                    self.direction = direction
                }
                public enum CodingKeys: String, CodingKey {
                    case field
                    case direction
                }
            }
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchQuerySchema/sort`.
            public typealias SortPayload = [Components.Schemas.BlogTagListItemSearchQuerySchema.SortPayloadPayload]
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchQuerySchema/sort`.
            public var sort: Components.Schemas.BlogTagListItemSearchQuerySchema.SortPayload?
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchQuerySchema/filters`.
            public struct FiltersPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchQuerySchema/filters/search`.
                public var search: Components.Schemas.SearchStringField?
                /// Creates a new `FiltersPayload`.
                ///
                /// - Parameters:
                ///   - search:
                public init(search: Components.Schemas.SearchStringField? = nil) {
                    self.search = search
                }
                public enum CodingKeys: String, CodingKey {
                    case search
                }
            }
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchQuerySchema/filters`.
            public var filters: Components.Schemas.BlogTagListItemSearchQuerySchema.FiltersPayload
            /// Creates a new `BlogTagListItemSearchQuerySchema`.
            ///
            /// - Parameters:
            ///   - page:
            ///   - sort:
            ///   - filters:
            public init(
                page: Components.Schemas.SearchPageSchema,
                sort: Components.Schemas.BlogTagListItemSearchQuerySchema.SortPayload? = nil,
                filters: Components.Schemas.BlogTagListItemSearchQuerySchema.FiltersPayload
            ) {
                self.page = page
                self.sort = sort
                self.filters = filters
            }
            public enum CodingKeys: String, CodingKey {
                case page
                case sort
                case filters
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchSchema`.
        public struct BlogTagListItemSearchSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchSchema/query`.
            public var query: Components.Schemas.BlogTagListItemSearchQuerySchema
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchSchema/data`.
            public struct DataPayload: Codable, Hashable, Sendable {
                /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchSchema/data/items`.
                public var items: [Components.Schemas.BlogTagListItemSchema]
                /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchSchema/data/total`.
                public var total: Swift.Int
                /// Creates a new `DataPayload`.
                ///
                /// - Parameters:
                ///   - items:
                ///   - total:
                public init(
                    items: [Components.Schemas.BlogTagListItemSchema],
                    total: Swift.Int
                ) {
                    self.items = items
                    self.total = total
                }
                public enum CodingKeys: String, CodingKey {
                    case items
                    case total
                }
            }
            /// - Remark: Generated from `#/components/schemas/BlogTagListItemSearchSchema/data`.
            public var data: Components.Schemas.BlogTagListItemSearchSchema.DataPayload
            /// Creates a new `BlogTagListItemSearchSchema`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - data:
            public init(
                query: Components.Schemas.BlogTagListItemSearchQuerySchema,
                data: Components.Schemas.BlogTagListItemSearchSchema.DataPayload
            ) {
                self.query = query
                self.data = data
            }
            public enum CodingKeys: String, CodingKey {
                case query
                case data
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogTagPatchSchema`.
        public struct BlogTagPatchSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/BlogTagPatchSchema/title`.
            public var title: Components.Schemas.BlogTagTitleField?
            /// - Remark: Generated from `#/components/schemas/BlogTagPatchSchema/excerpt`.
            public var excerpt: Components.Schemas.BlogTagExcerptField?
            /// - Remark: Generated from `#/components/schemas/BlogTagPatchSchema/content`.
            public var content: Components.Schemas.BlogTagContentField?
            /// - Remark: Generated from `#/components/schemas/BlogTagPatchSchema/imageAssetId`.
            public var imageAssetId: Components.Schemas.BlogTagImageAssetIdField?
            /// Creates a new `BlogTagPatchSchema`.
            ///
            /// - Parameters:
            ///   - title:
            ///   - excerpt:
            ///   - content:
            ///   - imageAssetId:
            public init(
                title: Components.Schemas.BlogTagTitleField? = nil,
                excerpt: Components.Schemas.BlogTagExcerptField? = nil,
                content: Components.Schemas.BlogTagContentField? = nil,
                imageAssetId: Components.Schemas.BlogTagImageAssetIdField? = nil
            ) {
                self.title = title
                self.excerpt = excerpt
                self.content = content
                self.imageAssetId = imageAssetId
            }
            public enum CodingKeys: String, CodingKey {
                case title
                case excerpt
                case content
                case imageAssetId
            }
        }
        /// - Remark: Generated from `#/components/schemas/BlogTagContentField`.
        public typealias BlogTagContentField = Swift.String
    }
}

// swift-openapi-generator dummy public import compatibility
public func unsafeOpenAPIGenerationHotfixForAppBlogModuleAdminTypesComponentsSchemas(
    _ url: Foundation.URL,
    _ data: Foundation.Data,
    _ date: Foundation.Date,
    _ runtimeConfiguration: OpenAPIRuntime.Configuration
) {
    fatalError()
}
