// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency @unsafe public import struct Foundation.URL
@preconcurrency @unsafe public import struct Foundation.Data
@preconcurrency @unsafe public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// - Remark: HTTP `POST /api/v1/account/register`.
    /// - Remark: Generated from `#/paths//api/v1/account/register/post(accountRegister)`.
    func accountRegister(_ input: Operations.AccountRegister.Input) async throws -> Operations.AccountRegister.Output
    /// - Remark: HTTP `GET /api/v1/account/invitation/exchange`.
    /// - Remark: Generated from `#/paths//api/v1/account/invitation/exchange/get(accountInvitationValidation)`.
    func accountInvitationValidation(_ input: Operations.AccountInvitationValidation.Input) async throws -> Operations.AccountInvitationValidation.Output
    /// - Remark: HTTP `POST /api/v1/account/invitation/exchange`.
    /// - Remark: Generated from `#/paths//api/v1/account/invitation/exchange/post(accountInvitationExchange)`.
    func accountInvitationExchange(_ input: Operations.AccountInvitationExchange.Input) async throws -> Operations.AccountInvitationExchange.Output
    /// - Remark: HTTP `GET /api/v1/account/settings`.
    /// - Remark: Generated from `#/paths//api/v1/account/settings/get(accountSettings)`.
    func accountSettings(_ input: Operations.AccountSettings.Input) async throws -> Operations.AccountSettings.Output
    /// - Remark: HTTP `GET /api/v1/account/profile`.
    /// - Remark: Generated from `#/paths//api/v1/account/profile/get(accountProfileGet)`.
    func accountProfileGet(_ input: Operations.AccountProfileGet.Input) async throws -> Operations.AccountProfileGet.Output
    /// - Remark: HTTP `PUT /api/v1/account/profile`.
    /// - Remark: Generated from `#/paths//api/v1/account/profile/put(accountProfileUpdate)`.
    func accountProfileUpdate(_ input: Operations.AccountProfileUpdate.Input) async throws -> Operations.AccountProfileUpdate.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `POST /api/v1/account/register`.
    /// - Remark: Generated from `#/paths//api/v1/account/register/post(accountRegister)`.
    public func accountRegister(
        headers: Operations.AccountRegister.Input.Headers = .init(),
        body: Components.RequestBodies.AccountRegisterRequestBody
    ) async throws -> Operations.AccountRegister.Output {
        try await accountRegister(Operations.AccountRegister.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/account/invitation/exchange`.
    /// - Remark: Generated from `#/paths//api/v1/account/invitation/exchange/get(accountInvitationValidation)`.
    public func accountInvitationValidation(
        query: Operations.AccountInvitationValidation.Input.Query,
        headers: Operations.AccountInvitationValidation.Input.Headers = .init()
    ) async throws -> Operations.AccountInvitationValidation.Output {
        try await accountInvitationValidation(Operations.AccountInvitationValidation.Input(
            query: query,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /api/v1/account/invitation/exchange`.
    /// - Remark: Generated from `#/paths//api/v1/account/invitation/exchange/post(accountInvitationExchange)`.
    public func accountInvitationExchange(
        headers: Operations.AccountInvitationExchange.Input.Headers = .init(),
        body: Components.RequestBodies.AccountInvitationExchangeRequestBody
    ) async throws -> Operations.AccountInvitationExchange.Output {
        try await accountInvitationExchange(Operations.AccountInvitationExchange.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/account/settings`.
    /// - Remark: Generated from `#/paths//api/v1/account/settings/get(accountSettings)`.
    public func accountSettings(headers: Operations.AccountSettings.Input.Headers = .init()) async throws -> Operations.AccountSettings.Output {
        try await accountSettings(Operations.AccountSettings.Input(headers: headers))
    }
    /// - Remark: HTTP `GET /api/v1/account/profile`.
    /// - Remark: Generated from `#/paths//api/v1/account/profile/get(accountProfileGet)`.
    public func accountProfileGet(headers: Operations.AccountProfileGet.Input.Headers = .init()) async throws -> Operations.AccountProfileGet.Output {
        try await accountProfileGet(Operations.AccountProfileGet.Input(headers: headers))
    }
    /// - Remark: HTTP `PUT /api/v1/account/profile`.
    /// - Remark: Generated from `#/paths//api/v1/account/profile/put(accountProfileUpdate)`.
    public func accountProfileUpdate(
        headers: Operations.AccountProfileUpdate.Input.Headers = .init(),
        body: Components.RequestBodies.AccountProfileUpdateRequestBody
    ) async throws -> Operations.AccountProfileUpdate.Output {
        try await accountProfileUpdate(Operations.AccountProfileUpdate.Input(
            headers: headers,
            body: body
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    public enum Server1 {
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
                variables: []
            )
        }
    }
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
            variables: []
        )
    }
}

// swift-openapi-generator dummy public import compatibility
public func unsafeOpenAPIGenerationHotfixForAppAccountModuleAppTypes(
    _ url: Foundation.URL,
    _ data: Foundation.Data,
    _ date: Foundation.Date,
    _ runtimeConfiguration: OpenAPIRuntime.Configuration
) {
    fatalError()
}
