// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime

#if os(Linux)
@preconcurrency @unsafe import struct Foundation.URL
@preconcurrency @unsafe import struct Foundation.Data
@preconcurrency @unsafe import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/AccountRegisterSchema`.
        public struct AccountRegisterSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/AccountRegisterSchema/email`.
            public var email: Components.Schemas.AccountRegisterEmailField
            /// - Remark: Generated from `#/components/schemas/AccountRegisterSchema/password`.
            public var password: Components.Schemas.AccountRegisterPasswordField
            /// Creates a new `AccountRegisterSchema`.
            ///
            /// - Parameters:
            ///   - email:
            ///   - password:
            public init(
                email: Components.Schemas.AccountRegisterEmailField,
                password: Components.Schemas.AccountRegisterPasswordField
            ) {
                self.email = email
                self.password = password
            }
            public enum CodingKeys: String, CodingKey {
                case email
                case password
            }
        }
        /// - Remark: Generated from `#/components/schemas/AccountRegisterEmailField`.
        public typealias AccountRegisterEmailField = Swift.String
        /// - Remark: Generated from `#/components/schemas/AccountRegisterPasswordField`.
        public typealias AccountRegisterPasswordField = Swift.String
        /// - Remark: Generated from `#/components/schemas/AccountAuthResponseSchema`.
        public struct AccountAuthResponseSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/AccountAuthResponseSchema/user`.
            public var user: Components.Schemas.UserIdentityDetailSchema
            /// - Remark: Generated from `#/components/schemas/AccountAuthResponseSchema/roles`.
            public var roles: [Swift.String]
            /// - Remark: Generated from `#/components/schemas/AccountAuthResponseSchema/permissions`.
            public var permissions: [Swift.String]
            /// - Remark: Generated from `#/components/schemas/AccountAuthResponseSchema/token`.
            public var token: Components.Schemas.AccountAuthTokenField
            /// Creates a new `AccountAuthResponseSchema`.
            ///
            /// - Parameters:
            ///   - user:
            ///   - roles:
            ///   - permissions:
            ///   - token:
            public init(
                user: Components.Schemas.UserIdentityDetailSchema,
                roles: [Swift.String],
                permissions: [Swift.String],
                token: Components.Schemas.AccountAuthTokenField
            ) {
                self.user = user
                self.roles = roles
                self.permissions = permissions
                self.token = token
            }
            public enum CodingKeys: String, CodingKey {
                case user
                case roles
                case permissions
                case token
            }
        }
        /// - Remark: Generated from `#/components/schemas/UserIdentityDetailSchema`.
        public struct UserIdentityDetailSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/UserIdentityDetailSchema/id`.
            public var id: Components.Schemas.UserIdentityIDField
            /// - Remark: Generated from `#/components/schemas/UserIdentityDetailSchema/name`.
            public var name: Components.Schemas.UserIdentityNameField
            /// - Remark: Generated from `#/components/schemas/UserIdentityDetailSchema/status`.
            public var status: Components.Schemas.UserIdentityStatusField
            /// - Remark: Generated from `#/components/schemas/UserIdentityDetailSchema/roleIds`.
            public var roleIds: Components.Schemas.UserIdentityRoleIDListSchema?
            /// Creates a new `UserIdentityDetailSchema`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - name:
            ///   - status:
            ///   - roleIds:
            public init(
                id: Components.Schemas.UserIdentityIDField,
                name: Components.Schemas.UserIdentityNameField,
                status: Components.Schemas.UserIdentityStatusField,
                roleIds: Components.Schemas.UserIdentityRoleIDListSchema? = nil
            ) {
                self.id = id
                self.name = name
                self.status = status
                self.roleIds = roleIds
            }
            public enum CodingKeys: String, CodingKey {
                case id
                case name
                case status
                case roleIds
            }
        }
        /// - Remark: Generated from `#/components/schemas/UserIdentityIDField`.
        public typealias UserIdentityIDField = Swift.String
        /// - Remark: Generated from `#/components/schemas/UserIdentityNameField`.
        public typealias UserIdentityNameField = Swift.String
        /// - Remark: Generated from `#/components/schemas/UserIdentityStatusField`.
        @frozen
        public enum UserIdentityStatusField: String, Codable, Hashable,
            Sendable, CaseIterable
        {
            case invited = "invited"
            case active = "active"
            case suspended = "suspended"
            case deactivated = "deactivated"
            case anonymized = "anonymized"
        }
        /// - Remark: Generated from `#/components/schemas/UserIdentityRoleIDListSchema`.
        public typealias UserIdentityRoleIDListSchema = [Swift.String]
        /// - Remark: Generated from `#/components/schemas/AccountAuthTokenField`.
        public typealias AccountAuthTokenField = Swift.String
        /// - Remark: Generated from `#/components/schemas/AccountAuthMagicLinkTokenField`.
        public typealias AccountAuthMagicLinkTokenField = Swift.String
        /// - Remark: Generated from `#/components/schemas/AccountInvitationValidationSchema`.
        public struct AccountInvitationValidationSchema: Codable, Hashable,
            Sendable
        {
            /// - Remark: Generated from `#/components/schemas/AccountInvitationValidationSchema/email`.
            public var email:
                Components.Schemas.AccountInvitationRegistrationEmailField
            /// - Remark: Generated from `#/components/schemas/AccountInvitationValidationSchema/expiresAt`.
            public var expiresAt:
                Components.Schemas.AccountInvitationRegistrationExpiresAtField
            /// Creates a new `AccountInvitationValidationSchema`.
            ///
            /// - Parameters:
            ///   - email:
            ///   - expiresAt:
            public init(
                email: Components.Schemas
                    .AccountInvitationRegistrationEmailField,
                expiresAt: Components.Schemas
                    .AccountInvitationRegistrationExpiresAtField
            ) {
                self.email = email
                self.expiresAt = expiresAt
            }
            public enum CodingKeys: String, CodingKey {
                case email
                case expiresAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/AccountInvitationRegistrationEmailField`.
        public typealias AccountInvitationRegistrationEmailField = Swift.String
        /// - Remark: Generated from `#/components/schemas/AccountInvitationRegistrationExpiresAtField`.
        public typealias AccountInvitationRegistrationExpiresAtField = Swift
            .Double
        /// - Remark: Generated from `#/components/schemas/AccountInvitationExchangeRequestSchema`.
        public struct AccountInvitationExchangeRequestSchema: Codable, Hashable,
            Sendable
        {
            /// - Remark: Generated from `#/components/schemas/AccountInvitationExchangeRequestSchema/token`.
            public var token: Components.Schemas.AccountAuthMagicLinkTokenField
            /// - Remark: Generated from `#/components/schemas/AccountInvitationExchangeRequestSchema/password`.
            public var password: Components.Schemas.AccountRegisterPasswordField
            /// Creates a new `AccountInvitationExchangeRequestSchema`.
            ///
            /// - Parameters:
            ///   - token:
            ///   - password:
            public init(
                token: Components.Schemas.AccountAuthMagicLinkTokenField,
                password: Components.Schemas.AccountRegisterPasswordField
            ) {
                self.token = token
                self.password = password
            }
            public enum CodingKeys: String, CodingKey {
                case token
                case password
            }
        }
        /// - Remark: Generated from `#/components/schemas/AccountSettingsResponseSchema`.
        public struct AccountSettingsResponseSchema: Codable, Hashable, Sendable
        {
            /// - Remark: Generated from `#/components/schemas/AccountSettingsResponseSchema/language`.
            public var language: Components.Schemas.AccountSettingsLanguageField
            /// - Remark: Generated from `#/components/schemas/AccountSettingsResponseSchema/timezone`.
            public var timezone: Components.Schemas.AccountSettingsTimezoneField
            /// - Remark: Generated from `#/components/schemas/AccountSettingsResponseSchema/pageSize`.
            public var pageSize: Components.Schemas.AccountSettingsPageSizeField
            /// Creates a new `AccountSettingsResponseSchema`.
            ///
            /// - Parameters:
            ///   - language:
            ///   - timezone:
            ///   - pageSize:
            public init(
                language: Components.Schemas.AccountSettingsLanguageField,
                timezone: Components.Schemas.AccountSettingsTimezoneField,
                pageSize: Components.Schemas.AccountSettingsPageSizeField
            ) {
                self.language = language
                self.timezone = timezone
                self.pageSize = pageSize
            }
            public enum CodingKeys: String, CodingKey {
                case language
                case timezone
                case pageSize
            }
        }
        /// - Remark: Generated from `#/components/schemas/AccountSettingsLanguageField`.
        public typealias AccountSettingsLanguageField = Swift.String
        /// - Remark: Generated from `#/components/schemas/AccountSettingsTimezoneField`.
        public typealias AccountSettingsTimezoneField = Swift.String
        /// - Remark: Generated from `#/components/schemas/AccountSettingsPageSizeField`.
        public typealias AccountSettingsPageSizeField = Swift.Int
        /// - Remark: Generated from `#/components/schemas/AccountProfileResponseSchema`.
        public struct AccountProfileResponseSchema: Codable, Hashable, Sendable
        {
            /// - Remark: Generated from `#/components/schemas/AccountProfileResponseSchema/firstName`.
            public var firstName: Swift.String?
            /// - Remark: Generated from `#/components/schemas/AccountProfileResponseSchema/lastName`.
            public var lastName: Swift.String?
            /// - Remark: Generated from `#/components/schemas/AccountProfileResponseSchema/profileImageAssetId`.
            public var profileImageAssetId: Swift.String?
            /// Creates a new `AccountProfileResponseSchema`.
            ///
            /// - Parameters:
            ///   - firstName:
            ///   - lastName:
            ///   - profileImageAssetId:
            public init(
                firstName: Swift.String? = nil,
                lastName: Swift.String? = nil,
                profileImageAssetId: Swift.String? = nil
            ) {
                self.firstName = firstName
                self.lastName = lastName
                self.profileImageAssetId = profileImageAssetId
            }
            public enum CodingKeys: String, CodingKey {
                case firstName
                case lastName
                case profileImageAssetId
            }
        }
        /// - Remark: Generated from `#/components/schemas/AccountProfileUpdateSchema`.
        public struct AccountProfileUpdateSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/AccountProfileUpdateSchema/firstName`.
            public var firstName: Swift.String?
            /// - Remark: Generated from `#/components/schemas/AccountProfileUpdateSchema/lastName`.
            public var lastName: Swift.String?
            /// - Remark: Generated from `#/components/schemas/AccountProfileUpdateSchema/profileImageAssetId`.
            public var profileImageAssetId: Swift.String?
            /// Creates a new `AccountProfileUpdateSchema`.
            ///
            /// - Parameters:
            ///   - firstName:
            ///   - lastName:
            ///   - profileImageAssetId:
            public init(
                firstName: Swift.String? = nil,
                lastName: Swift.String? = nil,
                profileImageAssetId: Swift.String? = nil
            ) {
                self.firstName = firstName
                self.lastName = lastName
                self.profileImageAssetId = profileImageAssetId
            }
            public enum CodingKeys: String, CodingKey {
                case firstName
                case lastName
                case profileImageAssetId
            }
        }
    }
}
