// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime

#if os(Linux)
@preconcurrency @unsafe public import struct Foundation.URL
@preconcurrency @unsafe public import struct Foundation.Data
@preconcurrency @unsafe public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// - Remark: HTTP `POST /api/v1/admin/redirect/rules`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules/post(redirectRuleCreate)`.
    func redirectRuleCreate(_ input: Operations.RedirectRuleCreate.Input)
        async throws -> Operations.RedirectRuleCreate.Output
    /// - Remark: HTTP `DELETE /api/v1/admin/redirect/rules`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules/delete(redirectRuleRemove)`.
    func redirectRuleRemove(_ input: Operations.RedirectRuleRemove.Input)
        async throws -> Operations.RedirectRuleRemove.Output
    /// - Remark: HTTP `GET /api/v1/admin/redirect/rules/`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules//get(redirectRuleList)`.
    func redirectRuleList(_ input: Operations.RedirectRuleList.Input)
        async throws -> Operations.RedirectRuleList.Output
    /// - Remark: HTTP `POST /api/v1/admin/redirect/rules/search`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules/search/post(redirectRuleSearch)`.
    func redirectRuleSearch(_ input: Operations.RedirectRuleSearch.Input)
        async throws -> Operations.RedirectRuleSearch.Output
    /// - Remark: HTTP `GET /api/v1/admin/redirect/rules/{redirectRuleId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules/{redirectRuleId}/get(redirectRuleGet)`.
    func redirectRuleGet(_ input: Operations.RedirectRuleGet.Input) async throws
        -> Operations.RedirectRuleGet.Output
    /// - Remark: HTTP `PATCH /api/v1/admin/redirect/rules/{redirectRuleId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules/{redirectRuleId}/patch(redirectRulePatch)`.
    func redirectRulePatch(_ input: Operations.RedirectRulePatch.Input)
        async throws -> Operations.RedirectRulePatch.Output
    /// - Remark: HTTP `PUT /api/v1/admin/redirect/rules/{redirectRuleId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules/{redirectRuleId}/put(redirectRuleUpdate)`.
    func redirectRuleUpdate(_ input: Operations.RedirectRuleUpdate.Input)
        async throws -> Operations.RedirectRuleUpdate.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `POST /api/v1/admin/redirect/rules`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules/post(redirectRuleCreate)`.
    public func redirectRuleCreate(
        headers: Operations.RedirectRuleCreate.Input.Headers = .init(),
        body: Components.RequestBodies.RedirectRuleRequestBody
    ) async throws -> Operations.RedirectRuleCreate.Output {
        try await redirectRuleCreate(
            Operations.RedirectRuleCreate.Input(
                headers: headers,
                body: body
            )
        )
    }
    /// - Remark: HTTP `DELETE /api/v1/admin/redirect/rules`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules/delete(redirectRuleRemove)`.
    public func redirectRuleRemove(
        headers: Operations.RedirectRuleRemove.Input.Headers = .init(),
        body: Components.RequestBodies.DeleteRequestBody
    ) async throws -> Operations.RedirectRuleRemove.Output {
        try await redirectRuleRemove(
            Operations.RedirectRuleRemove.Input(
                headers: headers,
                body: body
            )
        )
    }
    /// - Remark: HTTP `GET /api/v1/admin/redirect/rules/`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules//get(redirectRuleList)`.
    public func redirectRuleList(
        headers: Operations.RedirectRuleList.Input.Headers = .init()
    ) async throws -> Operations.RedirectRuleList.Output {
        try await redirectRuleList(
            Operations.RedirectRuleList.Input(headers: headers)
        )
    }
    /// - Remark: HTTP `POST /api/v1/admin/redirect/rules/search`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules/search/post(redirectRuleSearch)`.
    public func redirectRuleSearch(
        headers: Operations.RedirectRuleSearch.Input.Headers = .init(),
        body: Operations.RedirectRuleSearch.Input.Body
    ) async throws -> Operations.RedirectRuleSearch.Output {
        try await redirectRuleSearch(
            Operations.RedirectRuleSearch.Input(
                headers: headers,
                body: body
            )
        )
    }
    /// - Remark: HTTP `GET /api/v1/admin/redirect/rules/{redirectRuleId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules/{redirectRuleId}/get(redirectRuleGet)`.
    public func redirectRuleGet(
        path: Operations.RedirectRuleGet.Input.Path,
        headers: Operations.RedirectRuleGet.Input.Headers = .init()
    ) async throws -> Operations.RedirectRuleGet.Output {
        try await redirectRuleGet(
            Operations.RedirectRuleGet.Input(
                path: path,
                headers: headers
            )
        )
    }
    /// - Remark: HTTP `PATCH /api/v1/admin/redirect/rules/{redirectRuleId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules/{redirectRuleId}/patch(redirectRulePatch)`.
    public func redirectRulePatch(
        path: Operations.RedirectRulePatch.Input.Path,
        headers: Operations.RedirectRulePatch.Input.Headers = .init(),
        body: Components.RequestBodies.RedirectRulePatchRequestBody
    ) async throws -> Operations.RedirectRulePatch.Output {
        try await redirectRulePatch(
            Operations.RedirectRulePatch.Input(
                path: path,
                headers: headers,
                body: body
            )
        )
    }
    /// - Remark: HTTP `PUT /api/v1/admin/redirect/rules/{redirectRuleId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/redirect/rules/{redirectRuleId}/put(redirectRuleUpdate)`.
    public func redirectRuleUpdate(
        path: Operations.RedirectRuleUpdate.Input.Path,
        headers: Operations.RedirectRuleUpdate.Input.Headers = .init(),
        body: Components.RequestBodies.RedirectRuleUpdateRequestBody
    ) async throws -> Operations.RedirectRuleUpdate.Output {
        try await redirectRuleUpdate(
            Operations.RedirectRuleUpdate.Input(
                path: path,
                headers: headers,
                body: body
            )
        )
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    public enum Server1 {
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
                variables: []
            )
        }
    }
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
            variables: []
        )
    }
}

// swift-openapi-generator dummy public import compatibility
public func unsafeOpenAPIGenerationHotfixForAppRedirectModuleAdminTypes(
    _ url: Foundation.URL,
    _ data: Foundation.Data,
    _ date: Foundation.Date,
    _ runtimeConfiguration: OpenAPIRuntime.Configuration
) {
    fatalError()
}
