import HTTPTypes
// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime

#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
public struct Client: APIProtocol {
    /// The underlying HTTP client.
    private let client: UniversalClient
    /// Creates a new client.
    /// - Parameters:
    ///   - serverURL: The server URL that the client connects to. Any server
    ///   URLs defined in the OpenAPI document are available as static methods
    ///   on the ``Servers`` type.
    ///   - configuration: A set of configuration values for the client.
    ///   - transport: A transport that performs HTTP operations.
    ///   - middlewares: A list of middlewares to call before the transport.
    public init(
        serverURL: Foundation.URL,
        configuration: Configuration = .init(),
        transport: any ClientTransport,
        middlewares: [any ClientMiddleware] = []
    ) {
        self.client = .init(
            serverURL: serverURL,
            configuration: configuration,
            transport: transport,
            middlewares: middlewares
        )
    }
    private var converter: Converter {
        client.converter
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/assets`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/post(mediaAssetCreate)`.
    public func mediaAssetCreate(_ input: Operations.MediaAssetCreate.Input)
        async throws -> Operations.MediaAssetCreate.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.MediaAssetCreate.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/assets",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 201:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.MediaAssetDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.MediaAssetDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .created(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `DELETE /api/v1/admin/media/assets`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/delete(mediaAssetDelete)`.
    public func mediaAssetDelete(_ input: Operations.MediaAssetDelete.Input)
        async throws -> Operations.MediaAssetDelete.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.MediaAssetDelete.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/assets",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .delete
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.DeleteResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.DeleteResponseSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/assets/search`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/search/post(mediaAssetSearch)`.
    public func mediaAssetSearch(_ input: Operations.MediaAssetSearch.Input)
        async throws -> Operations.MediaAssetSearch.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.MediaAssetSearch.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/assets/search",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses
                            .MediaAssetListItemSearchSchemaSearchResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.MediaAssetListItemSearchSchema
                                .self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /api/v1/admin/media/assets/{mediaAssetId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/{mediaAssetId}/get(mediaAssetGet)`.
    public func mediaAssetGet(_ input: Operations.MediaAssetGet.Input)
        async throws -> Operations.MediaAssetGet.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.MediaAssetGet.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/assets/{}",
                    parameters: [
                        input.path.mediaAssetId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.MediaAssetDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.MediaAssetDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `PATCH /api/v1/admin/media/assets/{mediaAssetId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/{mediaAssetId}/patch(mediaAssetUpdate)`.
    public func mediaAssetUpdate(_ input: Operations.MediaAssetUpdate.Input)
        async throws -> Operations.MediaAssetUpdate.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.MediaAssetUpdate.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/assets/{}",
                    parameters: [
                        input.path.mediaAssetId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .patch
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.MediaAssetDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.MediaAssetDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /api/v1/admin/media/assets/{mediaAssetId}/variants`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/{mediaAssetId}/variants/get(mediaAssetVariantSearch)`.
    public func mediaAssetVariantSearch(
        _ input: Operations.MediaAssetVariantSearch.Input
    ) async throws -> Operations.MediaAssetVariantSearch.Output {
        try await client.send(
            input: input,
            forOperation: Operations.MediaAssetVariantSearch.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/assets/{}/variants",
                    parameters: [
                        input.path.mediaAssetId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses.MediaAssetVariantListResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.MediaAssetVariantListSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/folders`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/post(mediaFolderCreate)`.
    public func mediaFolderCreate(_ input: Operations.MediaFolderCreate.Input)
        async throws -> Operations.MediaFolderCreate.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.MediaFolderCreate.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/folders",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 201:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses.MediaFolderDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.MediaFolderDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .created(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `DELETE /api/v1/admin/media/folders`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/delete(mediaFolderDelete)`.
    public func mediaFolderDelete(_ input: Operations.MediaFolderDelete.Input)
        async throws -> Operations.MediaFolderDelete.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.MediaFolderDelete.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/folders",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .delete
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.DeleteResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.DeleteResponseSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/folders/search`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/search/post(mediaFolderSearch)`.
    public func mediaFolderSearch(_ input: Operations.MediaFolderSearch.Input)
        async throws -> Operations.MediaFolderSearch.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.MediaFolderSearch.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/folders/search",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses
                            .MediaFolderListItemSearchSchemaSearchResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.MediaFolderListItemSearchSchema
                                .self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /api/v1/admin/media/folders/{mediaFolderId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/{mediaFolderId}/get(mediaFolderGet)`.
    public func mediaFolderGet(_ input: Operations.MediaFolderGet.Input)
        async throws -> Operations.MediaFolderGet.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.MediaFolderGet.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/folders/{}",
                    parameters: [
                        input.path.mediaFolderId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses.MediaFolderDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.MediaFolderDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `PATCH /api/v1/admin/media/folders/{mediaFolderId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/{mediaFolderId}/patch(mediaFolderUpdate)`.
    public func mediaFolderUpdate(_ input: Operations.MediaFolderUpdate.Input)
        async throws -> Operations.MediaFolderUpdate.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.MediaFolderUpdate.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/folders/{}",
                    parameters: [
                        input.path.mediaFolderId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .patch
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses.MediaFolderDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.MediaFolderDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/processors`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/processors/post(mediaProcessorCreate)`.
    public func mediaProcessorCreate(
        _ input: Operations.MediaProcessorCreate.Input
    ) async throws -> Operations.MediaProcessorCreate.Output {
        try await client.send(
            input: input,
            forOperation: Operations.MediaProcessorCreate.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/processors",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 201:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses.MediaProcessorDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.MediaProcessorDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .created(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `DELETE /api/v1/admin/media/processors`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/processors/delete(mediaProcessorDelete)`.
    public func mediaProcessorDelete(
        _ input: Operations.MediaProcessorDelete.Input
    ) async throws -> Operations.MediaProcessorDelete.Output {
        try await client.send(
            input: input,
            forOperation: Operations.MediaProcessorDelete.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/processors",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .delete
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.DeleteResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.DeleteResponseSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/processors/search`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/processors/search/post(mediaProcessorSearch)`.
    public func mediaProcessorSearch(
        _ input: Operations.MediaProcessorSearch.Input
    ) async throws -> Operations.MediaProcessorSearch.Output {
        try await client.send(
            input: input,
            forOperation: Operations.MediaProcessorSearch.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/processors/search",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses
                            .MediaProcessorListItemSearchSchemaSearchResponse
                            .Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas
                                .MediaProcessorListItemSearchSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /api/v1/admin/media/processors/{mediaProcessorId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/processors/{mediaProcessorId}/get(mediaProcessorGet)`.
    public func mediaProcessorGet(_ input: Operations.MediaProcessorGet.Input)
        async throws -> Operations.MediaProcessorGet.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.MediaProcessorGet.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/processors/{}",
                    parameters: [
                        input.path.mediaProcessorId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses.MediaProcessorDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.MediaProcessorDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `PATCH /api/v1/admin/media/processors/{mediaProcessorId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/processors/{mediaProcessorId}/patch(mediaProcessorUpdate)`.
    public func mediaProcessorUpdate(
        _ input: Operations.MediaProcessorUpdate.Input
    ) async throws -> Operations.MediaProcessorUpdate.Output {
        try await client.send(
            input: input,
            forOperation: Operations.MediaProcessorUpdate.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/media/processors/{}",
                    parameters: [
                        input.path.mediaProcessorId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .patch
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses.MediaProcessorDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.MediaProcessorDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
}
