// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// - Remark: HTTP `POST /api/v1/admin/media/assets`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/post(mediaAssetCreate)`.
    func mediaAssetCreate(_ input: Operations.MediaAssetCreate.Input) async throws -> Operations.MediaAssetCreate.Output
    /// - Remark: HTTP `DELETE /api/v1/admin/media/assets`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/delete(mediaAssetNodeRemove)`.
    func mediaAssetNodeRemove(_ input: Operations.MediaAssetNodeRemove.Input) async throws -> Operations.MediaAssetNodeRemove.Output
    /// - Remark: HTTP `POST /api/v1/admin/media/assets/list`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/list/post(mediaAssetList)`.
    func mediaAssetList(_ input: Operations.MediaAssetList.Input) async throws -> Operations.MediaAssetList.Output
    /// - Remark: HTTP `POST /api/v1/admin/media/assets/resolve`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/resolve/post(mediaAssetResolve)`.
    func mediaAssetResolve(_ input: Operations.MediaAssetResolve.Input) async throws -> Operations.MediaAssetResolve.Output
    /// - Remark: HTTP `GET /api/v1/admin/media/assets/{mediaAssetId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/{mediaAssetId}/get(mediaAssetGet)`.
    func mediaAssetGet(_ input: Operations.MediaAssetGet.Input) async throws -> Operations.MediaAssetGet.Output
    /// - Remark: HTTP `PATCH /api/v1/admin/media/assets/{mediaAssetId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/{mediaAssetId}/patch(mediaAssetUpdate)`.
    func mediaAssetUpdate(_ input: Operations.MediaAssetUpdate.Input) async throws -> Operations.MediaAssetUpdate.Output
    /// - Remark: HTTP `GET /api/v1/admin/media/assets/{mediaAssetId}/variants`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/{mediaAssetId}/variants/get(mediaAssetVariantSearch)`.
    func mediaAssetVariantSearch(_ input: Operations.MediaAssetVariantSearch.Input) async throws -> Operations.MediaAssetVariantSearch.Output
    /// - Remark: HTTP `POST /api/v1/admin/media/folders`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/post(mediaFolderCreate)`.
    func mediaFolderCreate(_ input: Operations.MediaFolderCreate.Input) async throws -> Operations.MediaFolderCreate.Output
    /// - Remark: HTTP `POST /api/v1/admin/media/folders/list`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/list/post(mediaFolderList)`.
    func mediaFolderList(_ input: Operations.MediaFolderList.Input) async throws -> Operations.MediaFolderList.Output
    /// - Remark: HTTP `GET /api/v1/admin/media/folders/{mediaFolderId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/{mediaFolderId}/get(mediaFolderGet)`.
    func mediaFolderGet(_ input: Operations.MediaFolderGet.Input) async throws -> Operations.MediaFolderGet.Output
    /// - Remark: HTTP `PATCH /api/v1/admin/media/folders/{mediaFolderId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/{mediaFolderId}/patch(mediaFolderUpdate)`.
    func mediaFolderUpdate(_ input: Operations.MediaFolderUpdate.Input) async throws -> Operations.MediaFolderUpdate.Output
    /// - Remark: HTTP `POST /api/v1/admin/media/variants`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/post(mediaVariantCreate)`.
    func mediaVariantCreate(_ input: Operations.MediaVariantCreate.Input) async throws -> Operations.MediaVariantCreate.Output
    /// - Remark: HTTP `DELETE /api/v1/admin/media/variants`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/delete(mediaVariantRemove)`.
    func mediaVariantRemove(_ input: Operations.MediaVariantRemove.Input) async throws -> Operations.MediaVariantRemove.Output
    /// - Remark: HTTP `POST /api/v1/admin/media/variants/list`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/list/post(mediaVariantList)`.
    func mediaVariantList(_ input: Operations.MediaVariantList.Input) async throws -> Operations.MediaVariantList.Output
    /// - Remark: HTTP `GET /api/v1/admin/media/variants/{mediaVariantId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/get(mediaVariantGet)`.
    func mediaVariantGet(_ input: Operations.MediaVariantGet.Input) async throws -> Operations.MediaVariantGet.Output
    /// - Remark: HTTP `PATCH /api/v1/admin/media/variants/{mediaVariantId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/patch(mediaVariantUpdate)`.
    func mediaVariantUpdate(_ input: Operations.MediaVariantUpdate.Input) async throws -> Operations.MediaVariantUpdate.Output
    /// - Remark: HTTP `POST /api/v1/admin/media/variants/{mediaVariantId}/processors`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/processors/post(mediaVariantProcessorCreate)`.
    func mediaVariantProcessorCreate(_ input: Operations.MediaVariantProcessorCreate.Input) async throws -> Operations.MediaVariantProcessorCreate.Output
    /// - Remark: HTTP `DELETE /api/v1/admin/media/variants/{mediaVariantId}/processors`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/processors/delete(mediaVariantProcessorRemove)`.
    func mediaVariantProcessorRemove(_ input: Operations.MediaVariantProcessorRemove.Input) async throws -> Operations.MediaVariantProcessorRemove.Output
    /// - Remark: HTTP `POST /api/v1/admin/media/variants/{mediaVariantId}/processors/list`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/processors/list/post(mediaVariantProcessorList)`.
    func mediaVariantProcessorList(_ input: Operations.MediaVariantProcessorList.Input) async throws -> Operations.MediaVariantProcessorList.Output
    /// - Remark: HTTP `GET /api/v1/admin/media/variants/{mediaVariantId}/processors/{mediaVariantProcessorId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/processors/{mediaVariantProcessorId}/get(mediaVariantProcessorGet)`.
    func mediaVariantProcessorGet(_ input: Operations.MediaVariantProcessorGet.Input) async throws -> Operations.MediaVariantProcessorGet.Output
    /// - Remark: HTTP `PATCH /api/v1/admin/media/variants/{mediaVariantId}/processors/{mediaVariantProcessorId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/processors/{mediaVariantProcessorId}/patch(mediaVariantProcessorUpdate)`.
    func mediaVariantProcessorUpdate(_ input: Operations.MediaVariantProcessorUpdate.Input) async throws -> Operations.MediaVariantProcessorUpdate.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `POST /api/v1/admin/media/assets`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/post(mediaAssetCreate)`.
    public func mediaAssetCreate(
        headers: Operations.MediaAssetCreate.Input.Headers = .init(),
        body: Components.RequestBodies.MediaAssetCreateRequestBody
    ) async throws -> Operations.MediaAssetCreate.Output {
        try await mediaAssetCreate(Operations.MediaAssetCreate.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `DELETE /api/v1/admin/media/assets`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/delete(mediaAssetNodeRemove)`.
    public func mediaAssetNodeRemove(
        headers: Operations.MediaAssetNodeRemove.Input.Headers = .init(),
        body: Components.RequestBodies.DeleteRequestBody
    ) async throws -> Operations.MediaAssetNodeRemove.Output {
        try await mediaAssetNodeRemove(Operations.MediaAssetNodeRemove.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/assets/list`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/list/post(mediaAssetList)`.
    public func mediaAssetList(
        headers: Operations.MediaAssetList.Input.Headers = .init(),
        body: Operations.MediaAssetList.Input.Body
    ) async throws -> Operations.MediaAssetList.Output {
        try await mediaAssetList(Operations.MediaAssetList.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/assets/resolve`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/resolve/post(mediaAssetResolve)`.
    public func mediaAssetResolve(
        headers: Operations.MediaAssetResolve.Input.Headers = .init(),
        body: Components.RequestBodies.MediaAssetResolveRequestBody
    ) async throws -> Operations.MediaAssetResolve.Output {
        try await mediaAssetResolve(Operations.MediaAssetResolve.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/admin/media/assets/{mediaAssetId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/{mediaAssetId}/get(mediaAssetGet)`.
    public func mediaAssetGet(
        path: Operations.MediaAssetGet.Input.Path,
        headers: Operations.MediaAssetGet.Input.Headers = .init()
    ) async throws -> Operations.MediaAssetGet.Output {
        try await mediaAssetGet(Operations.MediaAssetGet.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PATCH /api/v1/admin/media/assets/{mediaAssetId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/{mediaAssetId}/patch(mediaAssetUpdate)`.
    public func mediaAssetUpdate(
        path: Operations.MediaAssetUpdate.Input.Path,
        headers: Operations.MediaAssetUpdate.Input.Headers = .init(),
        body: Components.RequestBodies.MediaAssetPatchRequestBody
    ) async throws -> Operations.MediaAssetUpdate.Output {
        try await mediaAssetUpdate(Operations.MediaAssetUpdate.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/admin/media/assets/{mediaAssetId}/variants`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/assets/{mediaAssetId}/variants/get(mediaAssetVariantSearch)`.
    public func mediaAssetVariantSearch(
        path: Operations.MediaAssetVariantSearch.Input.Path,
        headers: Operations.MediaAssetVariantSearch.Input.Headers = .init()
    ) async throws -> Operations.MediaAssetVariantSearch.Output {
        try await mediaAssetVariantSearch(Operations.MediaAssetVariantSearch.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/folders`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/post(mediaFolderCreate)`.
    public func mediaFolderCreate(
        headers: Operations.MediaFolderCreate.Input.Headers = .init(),
        body: Components.RequestBodies.MediaFolderCreateRequestBody
    ) async throws -> Operations.MediaFolderCreate.Output {
        try await mediaFolderCreate(Operations.MediaFolderCreate.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/folders/list`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/list/post(mediaFolderList)`.
    public func mediaFolderList(
        headers: Operations.MediaFolderList.Input.Headers = .init(),
        body: Operations.MediaFolderList.Input.Body
    ) async throws -> Operations.MediaFolderList.Output {
        try await mediaFolderList(Operations.MediaFolderList.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/admin/media/folders/{mediaFolderId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/{mediaFolderId}/get(mediaFolderGet)`.
    public func mediaFolderGet(
        path: Operations.MediaFolderGet.Input.Path,
        headers: Operations.MediaFolderGet.Input.Headers = .init()
    ) async throws -> Operations.MediaFolderGet.Output {
        try await mediaFolderGet(Operations.MediaFolderGet.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PATCH /api/v1/admin/media/folders/{mediaFolderId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/folders/{mediaFolderId}/patch(mediaFolderUpdate)`.
    public func mediaFolderUpdate(
        path: Operations.MediaFolderUpdate.Input.Path,
        headers: Operations.MediaFolderUpdate.Input.Headers = .init(),
        body: Components.RequestBodies.MediaFolderPatchRequestBody
    ) async throws -> Operations.MediaFolderUpdate.Output {
        try await mediaFolderUpdate(Operations.MediaFolderUpdate.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/variants`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/post(mediaVariantCreate)`.
    public func mediaVariantCreate(
        headers: Operations.MediaVariantCreate.Input.Headers = .init(),
        body: Components.RequestBodies.MediaVariantCreateRequestBody
    ) async throws -> Operations.MediaVariantCreate.Output {
        try await mediaVariantCreate(Operations.MediaVariantCreate.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `DELETE /api/v1/admin/media/variants`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/delete(mediaVariantRemove)`.
    public func mediaVariantRemove(
        headers: Operations.MediaVariantRemove.Input.Headers = .init(),
        body: Components.RequestBodies.DeleteRequestBody
    ) async throws -> Operations.MediaVariantRemove.Output {
        try await mediaVariantRemove(Operations.MediaVariantRemove.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/variants/list`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/list/post(mediaVariantList)`.
    public func mediaVariantList(
        headers: Operations.MediaVariantList.Input.Headers = .init(),
        body: Operations.MediaVariantList.Input.Body
    ) async throws -> Operations.MediaVariantList.Output {
        try await mediaVariantList(Operations.MediaVariantList.Input(
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/admin/media/variants/{mediaVariantId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/get(mediaVariantGet)`.
    public func mediaVariantGet(
        path: Operations.MediaVariantGet.Input.Path,
        headers: Operations.MediaVariantGet.Input.Headers = .init()
    ) async throws -> Operations.MediaVariantGet.Output {
        try await mediaVariantGet(Operations.MediaVariantGet.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PATCH /api/v1/admin/media/variants/{mediaVariantId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/patch(mediaVariantUpdate)`.
    public func mediaVariantUpdate(
        path: Operations.MediaVariantUpdate.Input.Path,
        headers: Operations.MediaVariantUpdate.Input.Headers = .init(),
        body: Components.RequestBodies.MediaVariantCreateRequestBody
    ) async throws -> Operations.MediaVariantUpdate.Output {
        try await mediaVariantUpdate(Operations.MediaVariantUpdate.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/variants/{mediaVariantId}/processors`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/processors/post(mediaVariantProcessorCreate)`.
    public func mediaVariantProcessorCreate(
        path: Operations.MediaVariantProcessorCreate.Input.Path,
        headers: Operations.MediaVariantProcessorCreate.Input.Headers = .init(),
        body: Components.RequestBodies.MediaVariantProcessorCreateRequestBody
    ) async throws -> Operations.MediaVariantProcessorCreate.Output {
        try await mediaVariantProcessorCreate(Operations.MediaVariantProcessorCreate.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `DELETE /api/v1/admin/media/variants/{mediaVariantId}/processors`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/processors/delete(mediaVariantProcessorRemove)`.
    public func mediaVariantProcessorRemove(
        path: Operations.MediaVariantProcessorRemove.Input.Path,
        headers: Operations.MediaVariantProcessorRemove.Input.Headers = .init(),
        body: Components.RequestBodies.DeleteRequestBody
    ) async throws -> Operations.MediaVariantProcessorRemove.Output {
        try await mediaVariantProcessorRemove(Operations.MediaVariantProcessorRemove.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `POST /api/v1/admin/media/variants/{mediaVariantId}/processors/list`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/processors/list/post(mediaVariantProcessorList)`.
    public func mediaVariantProcessorList(
        path: Operations.MediaVariantProcessorList.Input.Path,
        headers: Operations.MediaVariantProcessorList.Input.Headers = .init(),
        body: Operations.MediaVariantProcessorList.Input.Body
    ) async throws -> Operations.MediaVariantProcessorList.Output {
        try await mediaVariantProcessorList(Operations.MediaVariantProcessorList.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// - Remark: HTTP `GET /api/v1/admin/media/variants/{mediaVariantId}/processors/{mediaVariantProcessorId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/processors/{mediaVariantProcessorId}/get(mediaVariantProcessorGet)`.
    public func mediaVariantProcessorGet(
        path: Operations.MediaVariantProcessorGet.Input.Path,
        headers: Operations.MediaVariantProcessorGet.Input.Headers = .init()
    ) async throws -> Operations.MediaVariantProcessorGet.Output {
        try await mediaVariantProcessorGet(Operations.MediaVariantProcessorGet.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `PATCH /api/v1/admin/media/variants/{mediaVariantId}/processors/{mediaVariantProcessorId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/media/variants/{mediaVariantId}/processors/{mediaVariantProcessorId}/patch(mediaVariantProcessorUpdate)`.
    public func mediaVariantProcessorUpdate(
        path: Operations.MediaVariantProcessorUpdate.Input.Path,
        headers: Operations.MediaVariantProcessorUpdate.Input.Headers = .init(),
        body: Components.RequestBodies.MediaVariantProcessorCreateRequestBody
    ) async throws -> Operations.MediaVariantProcessorUpdate.Output {
        try await mediaVariantProcessorUpdate(Operations.MediaVariantProcessorUpdate.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    public enum Server1 {
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
                variables: []
            )
        }
    }
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
            variables: []
        )
    }
}
