// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime

#if os(Linux)
@preconcurrency @unsafe public import struct Foundation.URL
@preconcurrency @unsafe public import struct Foundation.Data
@preconcurrency @unsafe public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// Types generated from the components section of the OpenAPI document.
public enum Components {}

// swift-openapi-generator dummy public import compatibility
public func unsafeOpenAPIGenerationHotfixForAppMediaModuleAdminTypesComponents(
    _ url: Foundation.URL,
    _ data: Foundation.Data,
    _ date: Foundation.Date,
    _ runtimeConfiguration: OpenAPIRuntime.Configuration
) {
    fatalError()
}
