// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency @unsafe public import struct Foundation.URL
@preconcurrency @unsafe public import struct Foundation.Data
@preconcurrency @unsafe public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {
        public struct NewsletterCampaignListResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/NewsletterCampaignListResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/NewsletterCampaignListResponse/content/application\/json`.
                case json(Components.Schemas.NewsletterCampaignListSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.NewsletterCampaignListSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.NewsletterCampaignListResponse.Body
            /// Creates a new `NewsletterCampaignListResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.NewsletterCampaignListResponse.Body) {
                self.body = body
            }
        }
        public struct NewsletterCampaignResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/NewsletterCampaignResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/NewsletterCampaignResponse/content/application\/json`.
                case json(Components.Schemas.NewsletterCampaignSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.NewsletterCampaignSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.NewsletterCampaignResponse.Body
            /// Creates a new `NewsletterCampaignResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.NewsletterCampaignResponse.Body) {
                self.body = body
            }
        }
        public struct DeleteResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/DeleteResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/DeleteResponse/content/application\/json`.
                case json(Components.Schemas.DeleteResponseSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.DeleteResponseSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.DeleteResponse.Body
            /// Creates a new `DeleteResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.DeleteResponse.Body) {
                self.body = body
            }
        }
        public struct NewsletterIssueListResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/NewsletterIssueListResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/NewsletterIssueListResponse/content/application\/json`.
                case json(Components.Schemas.NewsletterIssueListSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.NewsletterIssueListSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.NewsletterIssueListResponse.Body
            /// Creates a new `NewsletterIssueListResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.NewsletterIssueListResponse.Body) {
                self.body = body
            }
        }
        public struct NewsletterIssueResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/NewsletterIssueResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/NewsletterIssueResponse/content/application\/json`.
                case json(Components.Schemas.NewsletterIssueSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.NewsletterIssueSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.NewsletterIssueResponse.Body
            /// Creates a new `NewsletterIssueResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.NewsletterIssueResponse.Body) {
                self.body = body
            }
        }
        public struct NewsletterDeliveryListResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/NewsletterDeliveryListResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/NewsletterDeliveryListResponse/content/application\/json`.
                case json(Components.Schemas.NewsletterDeliveryListSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.NewsletterDeliveryListSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.NewsletterDeliveryListResponse.Body
            /// Creates a new `NewsletterDeliveryListResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.NewsletterDeliveryListResponse.Body) {
                self.body = body
            }
        }
        public struct NewsletterSubscriberListResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/NewsletterSubscriberListResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/NewsletterSubscriberListResponse/content/application\/json`.
                case json(Components.Schemas.NewsletterSubscriberListSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.NewsletterSubscriberListSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.NewsletterSubscriberListResponse.Body
            /// Creates a new `NewsletterSubscriberListResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.NewsletterSubscriberListResponse.Body) {
                self.body = body
            }
        }
        public struct NewsletterSubscriberResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/NewsletterSubscriberResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/NewsletterSubscriberResponse/content/application\/json`.
                case json(Components.Schemas.NewsletterSubscriberSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.NewsletterSubscriberSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.NewsletterSubscriberResponse.Body
            /// Creates a new `NewsletterSubscriberResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.NewsletterSubscriberResponse.Body) {
                self.body = body
            }
        }
    }
}

// swift-openapi-generator dummy public import compatibility
public func unsafeOpenAPIGenerationHotfixForAppNewsletterModuleAdminTypesComponentsResponses(
    _ url: Foundation.URL,
    _ data: Foundation.Data,
    _ date: Foundation.Date,
    _ runtimeConfiguration: OpenAPIRuntime.Configuration
) {
    fatalError()
}
