server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(yaml|yml)$ {
        default_type application/yaml;
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }
}
