openapi: 3.2.0
info:
  title: App API
  version: 0.1.0
tags:
- name: MediaAssets
  description: Public media assets.
servers:
- url: http://127.0.0.1:8080/
paths:
  /api/v1/media/assets/resolve:
    post:
      tags:
      - MediaAssets
      operationId: mediaAssetResolve
      requestBody:
        $ref: '#/components/requestBodies/MediaAssetResolveRequestBody'
      responses:
        200:
          $ref: '#/components/responses/MediaAssetResolveResponse'
components:
  schemas:
    MediaAssetResolveRequestSchema:
      type: object
      properties:
        ids:
          type: array
          items:
            type: string
            examples:
            - media_asset_1
          minItems: 0
          uniqueItems: false
        variants:
          $ref: '#/components/schemas/MediaAssetResolveVariantsField'
      required:
      - ids
      minProperties: 1
    MediaAssetResolveVariantsField:
      type: array
      items:
        type: string
        examples:
        - preview
      minItems: 0
      uniqueItems: false
    MediaAssetResolveSchema:
      type: array
      items:
        $ref: '#/components/schemas/MediaAssetResolveItemSchema'
      minItems: 0
      uniqueItems: false
    MediaAssetResolveItemSchema:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/MediaAssetIdField'
        url:
          type: string
          examples:
          - /media/assets/media_asset_1/cover-image.jpg
        variants:
          type: array
          items:
            $ref: '#/components/schemas/MediaAssetResolveVariantSchema'
          minItems: 0
          uniqueItems: false
      required:
      - id
      - url
      - variants
      minProperties: 3
    MediaAssetIdField:
      type: string
      examples:
      - media_asset_1
    MediaAssetResolveVariantSchema:
      type: object
      properties:
        key:
          $ref: '#/components/schemas/MediaAssetKeyField'
        url:
          type: string
          examples:
          - /media/assets/media_asset_1/cover-image.jpg
      required:
      - key
      - url
      minProperties: 2
    MediaAssetKeyField:
      type: string
      examples:
      - preview
  responses:
    MediaAssetResolveResponse:
      description: MediaAsset resolve response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MediaAssetResolveSchema'
  requestBodies:
    MediaAssetResolveRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MediaAssetResolveRequestSchema'
      required: true
