// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// - Remark: HTTP `GET /api/v1/web/settings`.
    /// - Remark: Generated from `#/paths//api/v1/web/settings/get(webSiteSettings)`.
    func webSiteSettings(_ input: Operations.WebSiteSettings.Input) async throws -> Operations.WebSiteSettings.Output
    /// - Remark: HTTP `GET /api/v1/web/menus`.
    /// - Remark: Generated from `#/paths//api/v1/web/menus/get(webMenuList)`.
    func webMenuList(_ input: Operations.WebMenuList.Input) async throws -> Operations.WebMenuList.Output
    /// - Remark: HTTP `GET /api/v1/web/routes/{slug}`.
    /// - Remark: Generated from `#/paths//api/v1/web/routes/{slug}/get(webMetadataGet)`.
    func webMetadataGet(_ input: Operations.WebMetadataGet.Input) async throws -> Operations.WebMetadataGet.Output
    /// - Remark: HTTP `GET /api/v1/web/pages/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/web/pages/{id}/get(webPageGet)`.
    func webPageGet(_ input: Operations.WebPageGet.Input) async throws -> Operations.WebPageGet.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `GET /api/v1/web/settings`.
    /// - Remark: Generated from `#/paths//api/v1/web/settings/get(webSiteSettings)`.
    public func webSiteSettings(headers: Operations.WebSiteSettings.Input.Headers = .init()) async throws -> Operations.WebSiteSettings.Output {
        try await webSiteSettings(Operations.WebSiteSettings.Input(headers: headers))
    }
    /// - Remark: HTTP `GET /api/v1/web/menus`.
    /// - Remark: Generated from `#/paths//api/v1/web/menus/get(webMenuList)`.
    public func webMenuList(headers: Operations.WebMenuList.Input.Headers = .init()) async throws -> Operations.WebMenuList.Output {
        try await webMenuList(Operations.WebMenuList.Input(headers: headers))
    }
    /// - Remark: HTTP `GET /api/v1/web/routes/{slug}`.
    /// - Remark: Generated from `#/paths//api/v1/web/routes/{slug}/get(webMetadataGet)`.
    public func webMetadataGet(
        path: Operations.WebMetadataGet.Input.Path,
        headers: Operations.WebMetadataGet.Input.Headers = .init()
    ) async throws -> Operations.WebMetadataGet.Output {
        try await webMetadataGet(Operations.WebMetadataGet.Input(
            path: path,
            headers: headers
        ))
    }
    /// - Remark: HTTP `GET /api/v1/web/pages/{id}`.
    /// - Remark: Generated from `#/paths//api/v1/web/pages/{id}/get(webPageGet)`.
    public func webPageGet(
        path: Operations.WebPageGet.Input.Path,
        headers: Operations.WebPageGet.Input.Headers = .init()
    ) async throws -> Operations.WebPageGet.Output {
        try await webPageGet(Operations.WebPageGet.Input(
            path: path,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    public enum Server1 {
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
                variables: []
            )
        }
    }
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
            variables: []
        )
    }
}
