// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime

#if os(Linux)
@preconcurrency @unsafe public import struct Foundation.URL
@preconcurrency @unsafe public import struct Foundation.Data
@preconcurrency @unsafe public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    public enum RequestBodies {
        /// - Remark: Generated from `#/components/requestBodies/ContactFormCreateRequestBody`.
        @frozen public enum ContactFormCreateRequestBody: Sendable, Hashable {
            /// - Remark: Generated from `#/components/requestBodies/ContactFormCreateRequestBody/content/application\/json`.
            case json(Components.Schemas.ContactFormCreateSchema)
        }
        /// - Remark: Generated from `#/components/requestBodies/DeleteRequestBody`.
        @frozen public enum DeleteRequestBody: Sendable, Hashable {
            /// - Remark: Generated from `#/components/requestBodies/DeleteRequestBody/content/application\/json`.
            case json(Components.Schemas.DeleteRequestSchema)
        }
        /// - Remark: Generated from `#/components/requestBodies/FormFieldCreateRequestBody`.
        @frozen public enum FormFieldCreateRequestBody: Sendable, Hashable {
            /// - Remark: Generated from `#/components/requestBodies/FormFieldCreateRequestBody/content/application\/json`.
            case json(Components.Schemas.FormFieldCreateSchema)
        }
        /// - Remark: Generated from `#/components/requestBodies/FormFieldPatchRequestBody`.
        @frozen public enum FormFieldPatchRequestBody: Sendable, Hashable {
            /// - Remark: Generated from `#/components/requestBodies/FormFieldPatchRequestBody/content/application\/json`.
            case json(Components.Schemas.FormFieldPatchSchema)
        }
        /// - Remark: Generated from `#/components/requestBodies/ContactFormSubmissionPatchRequestBody`.
        @frozen
        public enum ContactFormSubmissionPatchRequestBody: Sendable, Hashable {
            /// - Remark: Generated from `#/components/requestBodies/ContactFormSubmissionPatchRequestBody/content/application\/json`.
            case json(Components.Schemas.ContactFormSubmissionPatchSchema)
        }
    }
}

// swift-openapi-generator dummy public import compatibility
public func
    unsafeOpenAPIGenerationHotfixForAppContactModuleAdminTypesComponentsRequestBodies(
        _ url: Foundation.URL,
        _ data: Foundation.Data,
        _ date: Foundation.Date,
        _ runtimeConfiguration: OpenAPIRuntime.Configuration
    )
{
    fatalError()
}
