// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency @unsafe import struct Foundation.URL
@preconcurrency @unsafe import struct Foundation.Data
@preconcurrency @unsafe import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {
        /// - Remark: Generated from `#/components/parameters/ContactFormIdParameter`.
        public typealias ContactFormIdParameter = Components.Schemas.ContactIdField
        /// - Remark: Generated from `#/components/parameters/FormFieldIdParameter`.
        public typealias FormFieldIdParameter = Components.Schemas.ContactIdField
        /// - Remark: Generated from `#/components/parameters/ContactFormSubmissionIdParameter`.
        public typealias ContactFormSubmissionIdParameter = Components.Schemas.ContactIdField
    }
}
