// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {
        public struct ContactFormListResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/ContactFormListResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/ContactFormListResponse/content/application\/json`.
                case json(Components.Schemas.ContactFormListSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.ContactFormListSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.ContactFormListResponse.Body
            /// Creates a new `ContactFormListResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.ContactFormListResponse.Body) {
                self.body = body
            }
        }
        public struct ContactFormResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/ContactFormResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/ContactFormResponse/content/application\/json`.
                case json(Components.Schemas.ContactFormSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.ContactFormSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.ContactFormResponse.Body
            /// Creates a new `ContactFormResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.ContactFormResponse.Body) {
                self.body = body
            }
        }
        public struct DeleteResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/DeleteResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/DeleteResponse/content/application\/json`.
                case json(Components.Schemas.DeleteResponseSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.DeleteResponseSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.DeleteResponse.Body
            /// Creates a new `DeleteResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.DeleteResponse.Body) {
                self.body = body
            }
        }
        public struct FormFieldListResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/FormFieldListResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/FormFieldListResponse/content/application\/json`.
                case json(Components.Schemas.FormFieldListSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.FormFieldListSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.FormFieldListResponse.Body
            /// Creates a new `FormFieldListResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.FormFieldListResponse.Body) {
                self.body = body
            }
        }
        public struct FormFieldResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/FormFieldResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/FormFieldResponse/content/application\/json`.
                case json(Components.Schemas.FormFieldSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.FormFieldSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.FormFieldResponse.Body
            /// Creates a new `FormFieldResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.FormFieldResponse.Body) {
                self.body = body
            }
        }
        public struct ContactFormSubmissionListResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/ContactFormSubmissionListResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/ContactFormSubmissionListResponse/content/application\/json`.
                case json(Components.Schemas.ContactFormSubmissionListSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.ContactFormSubmissionListSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.ContactFormSubmissionListResponse.Body
            /// Creates a new `ContactFormSubmissionListResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.ContactFormSubmissionListResponse.Body) {
                self.body = body
            }
        }
        public struct ContactFormSubmissionResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/ContactFormSubmissionResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/ContactFormSubmissionResponse/content/application\/json`.
                case json(Components.Schemas.ContactFormSubmissionSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.ContactFormSubmissionSchema {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.ContactFormSubmissionResponse.Body
            /// Creates a new `ContactFormSubmissionResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.ContactFormSubmissionResponse.Body) {
                self.body = body
            }
        }
    }
}
