import HTTPTypes
// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime

#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
public struct Client: APIProtocol {
    /// The underlying HTTP client.
    private let client: UniversalClient
    /// Creates a new client.
    /// - Parameters:
    ///   - serverURL: The server URL that the client connects to. Any server
    ///   URLs defined in the OpenAPI document are available as static methods
    ///   on the ``Servers`` type.
    ///   - configuration: A set of configuration values for the client.
    ///   - transport: A transport that performs HTTP operations.
    ///   - middlewares: A list of middlewares to call before the transport.
    public init(
        serverURL: Foundation.URL,
        configuration: Configuration = .init(),
        transport: any ClientTransport,
        middlewares: [any ClientMiddleware] = []
    ) {
        self.client = .init(
            serverURL: serverURL,
            configuration: configuration,
            transport: transport,
            middlewares: middlewares
        )
    }
    private var converter: Converter {
        client.converter
    }
    /// Create user identity
    ///
    /// Creates an user identity
    ///
    /// - Remark: HTTP `POST /api/v1/admin/user/identities`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/identities/post(userIdentityCreate)`.
    public func userIdentityCreate(_ input: Operations.UserIdentityCreate.Input)
        async throws -> Operations.UserIdentityCreate.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserIdentityCreate.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/identities",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 201:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses.UserIdentityDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UserIdentityDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .created(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `DELETE /api/v1/admin/user/identities`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/identities/delete(userIdentityDelete)`.
    public func userIdentityDelete(_ input: Operations.UserIdentityDelete.Input)
        async throws -> Operations.UserIdentityDelete.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserIdentityDelete.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/identities",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .delete
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.DeleteResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.DeleteResponseSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /api/v1/admin/user/identities/`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/identities//get(userIdentityList)`.
    public func userIdentityList(_ input: Operations.UserIdentityList.Input)
        async throws -> Operations.UserIdentityList.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserIdentityList.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/identities/",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.UserIdentityListResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UserIdentityListSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /api/v1/admin/user/identities/search`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/identities/search/post(userIdentitySearch)`.
    public func userIdentitySearch(_ input: Operations.UserIdentitySearch.Input)
        async throws -> Operations.UserIdentitySearch.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserIdentitySearch.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/identities/search",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses
                            .UserIdentityListItemSearchSchemaSearchResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UserIdentityListItemSearchSchema
                                .self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /api/v1/admin/user/identities/{userIdentityId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/identities/{userIdentityId}/get(userIdentityGet)`.
    public func userIdentityGet(_ input: Operations.UserIdentityGet.Input)
        async throws -> Operations.UserIdentityGet.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserIdentityGet.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/identities/{}",
                    parameters: [
                        input.path.userIdentityId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses.UserIdentityDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UserIdentityDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `PATCH /api/v1/admin/user/identities/{userIdentityId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/identities/{userIdentityId}/patch(userIdentityPatch)`.
    public func userIdentityPatch(_ input: Operations.UserIdentityPatch.Input)
        async throws -> Operations.UserIdentityPatch.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserIdentityPatch.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/identities/{}",
                    parameters: [
                        input.path.userIdentityId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .patch
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses.UserIdentityDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UserIdentityDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `PUT /api/v1/admin/user/identities/{userIdentityId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/identities/{userIdentityId}/put(userIdentityUpdate)`.
    public func userIdentityUpdate(_ input: Operations.UserIdentityUpdate.Input)
        async throws -> Operations.UserIdentityUpdate.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserIdentityUpdate.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/identities/{}",
                    parameters: [
                        input.path.userIdentityId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .put
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses.UserIdentityDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UserIdentityDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /api/v1/admin/user/roles`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/roles/post(userRoleCreate)`.
    public func userRoleCreate(_ input: Operations.UserRoleCreate.Input)
        async throws -> Operations.UserRoleCreate.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserRoleCreate.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/roles",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 201:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.UserRoleDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UserRoleDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .created(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `DELETE /api/v1/admin/user/roles`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/roles/delete(userRoleDelete)`.
    public func userRoleDelete(_ input: Operations.UserRoleDelete.Input)
        async throws -> Operations.UserRoleDelete.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserRoleDelete.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/roles",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .delete
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.DeleteResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.DeleteResponseSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /api/v1/admin/user/roles/`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/roles//get(userRoleList)`.
    public func userRoleList(_ input: Operations.UserRoleList.Input)
        async throws -> Operations.UserRoleList.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserRoleList.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/roles/",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.UserRoleListResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UserRoleListSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `POST /api/v1/admin/user/roles/search`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/roles/search/post(userRoleSearch)`.
    public func userRoleSearch(_ input: Operations.UserRoleSearch.Input)
        async throws -> Operations.UserRoleSearch.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserRoleSearch.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/roles/search",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body:
                        Components.Responses
                            .UserRoleListItemSearchSchemaSearchResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UserRoleListItemSearchSchema
                                .self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `GET /api/v1/admin/user/roles/{userRoleId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/roles/{userRoleId}/get(userRoleGet)`.
    public func userRoleGet(_ input: Operations.UserRoleGet.Input) async throws
        -> Operations.UserRoleGet.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserRoleGet.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/roles/{}",
                    parameters: [
                        input.path.userRoleId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.UserRoleDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UserRoleDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `PATCH /api/v1/admin/user/roles/{userRoleId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/roles/{userRoleId}/patch(userRolePatch)`.
    public func userRolePatch(_ input: Operations.UserRolePatch.Input)
        async throws -> Operations.UserRolePatch.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserRolePatch.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/roles/{}",
                    parameters: [
                        input.path.userRoleId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .patch
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.UserRoleDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UserRoleDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// - Remark: HTTP `PUT /api/v1/admin/user/roles/{userRoleId}`.
    /// - Remark: Generated from `#/paths//api/v1/admin/user/roles/{userRoleId}/put(userRoleUpdate)`.
    public func userRoleUpdate(_ input: Operations.UserRoleUpdate.Input)
        async throws -> Operations.UserRoleUpdate.Output
    {
        try await client.send(
            input: input,
            forOperation: Operations.UserRoleUpdate.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/api/v1/admin/user/roles/{}",
                    parameters: [
                        input.path.userRoleId
                    ]
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .put
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case .json(let value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(
                        in: response.headerFields
                    )
                    let body: Components.Responses.UserRoleDetailResponse.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Components.Schemas.UserRoleDetailSchema.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure(
                            "bestContentType chose an invalid content type."
                        )
                    }
                    return .ok(.init(body: body))
                case 404:
                    return .notFound(.init())
                case 401:
                    return .unauthorized(.init())
                case 403:
                    return .forbidden(.init())
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
}
