// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime

#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// - Remark: HTTP `GET /api/v1/redirect/rules`.
    /// - Remark: Generated from `#/paths//api/v1/redirect/rules/get(redirectRuleGet)`.
    func redirectRuleGet(_ input: Operations.RedirectRuleGet.Input) async throws
        -> Operations.RedirectRuleGet.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// - Remark: HTTP `GET /api/v1/redirect/rules`.
    /// - Remark: Generated from `#/paths//api/v1/redirect/rules/get(redirectRuleGet)`.
    public func redirectRuleGet(
        query: Operations.RedirectRuleGet.Input.Query,
        headers: Operations.RedirectRuleGet.Input.Headers = .init()
    ) async throws -> Operations.RedirectRuleGet.Output {
        try await redirectRuleGet(
            Operations.RedirectRuleGet.Input(
                query: query,
                headers: headers
            )
        )
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    public enum Server1 {
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
                variables: []
            )
        }
    }
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "http://127.0.0.1:8080/",
            variables: []
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
public enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/RedirectSourceField`.
        public typealias RedirectSourceField = Swift.String
        /// - Remark: Generated from `#/components/schemas/RedirectRuleSchema`.
        public struct RedirectRuleSchema: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/RedirectRuleSchema/source`.
            public var source: Components.Schemas.RedirectSourceField
            /// - Remark: Generated from `#/components/schemas/RedirectRuleSchema/destination`.
            public var destination: Components.Schemas.RedirectDestinationField
            /// - Remark: Generated from `#/components/schemas/RedirectRuleSchema/statusCode`.
            public var statusCode: Components.Schemas.RedirectStatusCodeField
            /// Creates a new `RedirectRuleSchema`.
            ///
            /// - Parameters:
            ///   - source:
            ///   - destination:
            ///   - statusCode:
            public init(
                source: Components.Schemas.RedirectSourceField,
                destination: Components.Schemas.RedirectDestinationField,
                statusCode: Components.Schemas.RedirectStatusCodeField
            ) {
                self.source = source
                self.destination = destination
                self.statusCode = statusCode
            }
            public enum CodingKeys: String, CodingKey {
                case source
                case destination
                case statusCode
            }
        }
        /// - Remark: Generated from `#/components/schemas/RedirectDestinationField`.
        public typealias RedirectDestinationField = Swift.String
        /// - Remark: Generated from `#/components/schemas/RedirectStatusCodeField`.
        public typealias RedirectStatusCodeField = Swift.Int
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {
        /// Public redirect source path
        ///
        /// - Remark: Generated from `#/components/parameters/RedirectSourceParameter`.
        public typealias RedirectSourceParameter = Components.Schemas
            .RedirectSourceField
    }
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    public enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {
        public struct RedirectRuleResponse: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/RedirectRuleResponse/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/RedirectRuleResponse/content/application\/json`.
                case json(Components.Schemas.RedirectRuleSchema)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                public var json: Components.Schemas.RedirectRuleSchema {
                    get throws {
                        switch self {
                        case .json(let body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.RedirectRuleResponse.Body
            /// Creates a new `RedirectRuleResponse`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.RedirectRuleResponse.Body) {
                self.body = body
            }
        }
    }
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    public enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// - Remark: HTTP `GET /api/v1/redirect/rules`.
    /// - Remark: Generated from `#/paths//api/v1/redirect/rules/get(redirectRuleGet)`.
    public enum RedirectRuleGet {
        public static let id: Swift.String = "redirectRuleGet"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/api/v1/redirect/rules/GET/query`.
            public struct Query: Sendable, Hashable {
                /// Public redirect source path
                ///
                /// - Remark: Generated from `#/paths/api/v1/redirect/rules/GET/query/source`.
                public var source: Components.Parameters.RedirectSourceParameter
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - source: Public redirect source path
                public init(
                    source: Components.Parameters.RedirectSourceParameter
                ) {
                    self.source = source
                }
            }
            public var query: Operations.RedirectRuleGet.Input.Query
            /// - Remark: Generated from `#/paths/api/v1/redirect/rules/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept:
                    [OpenAPIRuntime.AcceptHeaderContentType<
                        Operations.RedirectRuleGet.AcceptableContentType
                    >]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<
                        Operations.RedirectRuleGet.AcceptableContentType
                    >] = .defaultValues()
                ) {
                    self.accept = accept
                }
            }
            public var headers: Operations.RedirectRuleGet.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - headers:
            public init(
                query: Operations.RedirectRuleGet.Input.Query,
                headers: Operations.RedirectRuleGet.Input.Headers = .init()
            ) {
                self.query = query
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            /// Redirect rule response
            ///
            /// - Remark: Generated from `#/paths//api/v1/redirect/rules/get(redirectRuleGet)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Components.Responses.RedirectRuleResponse)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Components.Responses.RedirectRuleResponse {
                get throws {
                    switch self {
                    case .ok(let response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct NotFound: Sendable, Hashable {
                /// Creates a new `NotFound`.
                public init() {}
            }
            /// Redirect rule not found
            ///
            /// - Remark: Generated from `#/paths//api/v1/redirect/rules/get(redirectRuleGet)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Operations.RedirectRuleGet.Output.NotFound)
            /// Redirect rule not found
            ///
            /// - Remark: Generated from `#/paths//api/v1/redirect/rules/get(redirectRuleGet)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            public static var notFound: Self {
                .notFound(.init())
            }
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            public var notFound: Operations.RedirectRuleGet.Output.NotFound {
                get throws {
                    switch self {
                    case .notFound(let response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(
                statusCode: Swift.Int,
                OpenAPIRuntime.UndocumentedPayload
            )
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case .other(let string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
